.TH "Accident Data" 3 "Thu Dec 11 2014" "Version v0.01" "VROOM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Accident Data \- 
.PP
This is the data for an Accident report\&.  

.SS "Modules"

.in +1c
.ti -1c
.RI "\fBPublic\fP"
.br
.ti -1c
.RI "\fBPrivate\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
This is the data for an Accident report\&. 


.PP
\fBNote:\fP
.RS 4
Comply eCall standards for MSD data structure\&. 
.PP
Complies MISRA 2004 standards 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for VROOM from the source code\&.
