.TH "Public" 3 "Thu Dec 11 2014" "Version v0.01" "VROOM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Public \- 
.SS "Modules"

.in +1c
.ti -1c
.RI "\fBFule types\fP"
.br
.RI "\fIConstant vehicle fuel type definition\&. \fP"
.ti -1c
.RI "\fBVehicle class\fP"
.br
.RI "\fIConstant vehicle class type definition\&. \fP"
.in -1c
.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBAD_MSD\fP"
.br
.RI "\fIstruct containing the MSD for an accident report \fP"
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBAD_EMERGENCY_FLAG\fP { \fBEMERGENCY_NO_ALARM\fP = 0U, \fBEMERGENCY_FALSE_ALARM\fP = 1U, \fBEMERGENCY_MANUAL_ALARM\fP = 2U, \fBEMERGENCY_AUTO_ALARM\fP = 3U, \fBEMERGENCY_ALARM_SENT\fP = 4U }"
.br
.RI "\fIFlag to detect if an alarm has been triggered\&. \fP"
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBad_emergency_alarm\fP (void)"
.br
.RI "\fIFunction to call when an emergency alarm is triggered\&. \fP"
.ti -1c
.RI "uint32_t \fBcalc_UTC_seconds\fP (\fBFIXED_TIME\fP *\fBbuf\fP)"
.br
.RI "\fICalculates UTC seconds since epoch\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 

.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBAD_EMERGENCY_FLAG\fP"

.PP
Flag to detect if an alarm has been triggered\&. 
.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIEMERGENCY_NO_ALARM \fP\fP
.TP
\fB\fIEMERGENCY_FALSE_ALARM \fP\fP
.TP
\fB\fIEMERGENCY_MANUAL_ALARM \fP\fP
.TP
\fB\fIEMERGENCY_AUTO_ALARM \fP\fP
.TP
\fB\fIEMERGENCY_ALARM_SENT \fP\fP
.PP
Definition at line 82 of file accident_data\&.h\&.
.SH "Function Documentation"
.PP 
.SS "void ad_emergency_alarm (void)"

.PP
Function to call when an emergency alarm is triggered\&. Starts the sequence required for placing an emergency call and send an MSD packet\&. Steps in function:
.br
.IP "1." 4
Record needed data
.br

.IP "2." 4
Create MSD structure
.br

.IP "3." 4
sent structure over FTP
.br

.IP "4." 4
call to emergency number
.PP
.PP
\fBParameters:\fP
.RS 4
\fIvoid\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
void 
.RE
.PP

.PP
Definition at line 38 of file accident_data\&.c\&.
.SS "uint32_t calc_UTC_seconds (\fBFIXED_TIME\fP *buf)"

.PP
Calculates UTC seconds since epoch\&. 
.PP
\fBParameters:\fP
.RS 4
\fIstruct\fP of \fBFIXED_TIME\fP
.RE
.PP
\fBReturns:\fP
.RS 4
UTC seconds as uint32_t
.RE
.PP
Calculates UTC seconds since EPOCH 
.PP
Definition at line 24 of file time\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for VROOM from the source code\&.
