.TH "Fule types" 3 "Wed Dec 3 2014" "Version v0.01" "VROOM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Fule types \- 
.PP
Constant vehicle fuel type definition\&.  

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBAD_FUEL_TYPE_OTHER\fP   0"
.br
.ti -1c
.RI "#define \fBAD_FUEL_TYPE_GASOLINE\fP   1"
.br
.ti -1c
.RI "#define \fBAD_FUEL_TYPE_DIESEL\fP   2"
.br
.ti -1c
.RI "#define \fBAD_FUEL_TYPE_NATURALGAS\fP   3"
.br
.ti -1c
.RI "#define \fBAD_FUEL_TYPE_PROPANE\fP   4"
.br
.ti -1c
.RI "#define \fBAD_FUEL_TYPE_ELECTRIC\fP   5"
.br
.ti -1c
.RI "#define \fBAD_FUEL_TYPE_HYDROGEN\fP   6"
.br
.in -1c
.SH "Detailed Description"
.PP 
Constant vehicle fuel type definition\&. 


.SH "Macro Definition Documentation"
.PP 
.SS "#define AD_FUEL_TYPE_DIESEL   2"

.PP
Definition at line 52 of file accident_data\&.h\&.
.SS "#define AD_FUEL_TYPE_ELECTRIC   5"

.PP
Definition at line 55 of file accident_data\&.h\&.
.SS "#define AD_FUEL_TYPE_GASOLINE   1"

.PP
Definition at line 51 of file accident_data\&.h\&.
.SS "#define AD_FUEL_TYPE_HYDROGEN   6"

.PP
Definition at line 56 of file accident_data\&.h\&.
.SS "#define AD_FUEL_TYPE_NATURALGAS   3"

.PP
Definition at line 53 of file accident_data\&.h\&.
.SS "#define AD_FUEL_TYPE_OTHER   0"

.PP
Definition at line 50 of file accident_data\&.h\&.
.SS "#define AD_FUEL_TYPE_PROPANE   4"

.PP
Definition at line 54 of file accident_data\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for VROOM from the source code\&.
