.TH "LIS331HH" 3 "Sun Nov 30 2014" "Version v0.01" "VROOM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
LIS331HH \- 
.SS "Modules"

.in +1c
.ti -1c
.RI "\fBPrivate\fP"
.br
.ti -1c
.RI "\fBPublic\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
This is a driver for the accelerometer LIS331HH on the ATMEGA family processors\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for VROOM from the source code\&.
