.TH "Scale Factor" 3 "Thu Dec 11 2014" "Version v0.01" "VROOM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Scale Factor \- 
.PP
Define for the scale factor to get calibrated output for 1g gravity This is visually calibrated to stationary have unit vector (1g)\&. The mathematically calculated value is: Full-scale g/(2^16) = 12/(2^16) = 0\&.00018310546875\&.  

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBACC_SCALE_FACTOR\fP   0\&.00017"
.br
.in -1c
.SH "Detailed Description"
.PP 
Define for the scale factor to get calibrated output for 1g gravity This is visually calibrated to stationary have unit vector (1g)\&. The mathematically calculated value is: Full-scale g/(2^16) = 12/(2^16) = 0\&.00018310546875\&. 


.SH "Macro Definition Documentation"
.PP 
.SS "#define ACC_SCALE_FACTOR   0\&.00017"

.PP
Definition at line 20 of file lis331hh\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for VROOM from the source code\&.
