.TH "D:/Dropbox/Skole Opgaver/ICT Engineering/7th Semester/Bachelor Project/Source Code/VROOM/VROOM_working/accident_logic/accident_detection.h" 3 "Thu Dec 11 2014" "Version v0.01" "VROOM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/Dropbox/Skole Opgaver/ICT Engineering/7th Semester/Bachelor Project/Source Code/VROOM/VROOM_working/accident_logic/accident_detection.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBcheck_for_crash\fP (void)"
.br
.RI "\fIChecks if a crash has occurred\&. \fP"
.ti -1c
.RI "void \fBcheck_for_fire\fP (void)"
.br
.RI "\fIChecks for fire\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 

.PP
\fBAuthor:\fP
.RS 4
Andi Degn 
.PP
Kenneth René Jensen 
.RE
.PP
\fBVersion:\fP
.RS 4
0\&.2 
.RE
.PP

.PP
Definition in file \fBaccident_detection\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for VROOM from the source code\&.
