.TH "D:/Dropbox/Skole Opgaver/ICT Engineering/7th Semester/Bachelor Project/Source Code/VROOM/VROOM_working/accident_logic/accident_detection.h" 3 "Wed Dec 3 2014" "Version v0.01" "VROOM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/Dropbox/Skole Opgaver/ICT Engineering/7th Semester/Bachelor Project/Source Code/VROOM/VROOM_working/accident_logic/accident_detection.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBaccident_detection_init\fP (void)"
.br
.RI "\fIInit detection for accidents\&. \fP"
.ti -1c
.RI "void \fBaccident_detection_start\fP (void)"
.br
.RI "\fIStarts detection for accidents\&. \fP"
.ti -1c
.RI "void \fBaccident_detection_stop\fP (void)"
.br
.RI "\fIStops detection for accidents\&. \fP"
.ti -1c
.RI "void \fBad_check_for_crash\fP (void)"
.br
.RI "\fIChecks if a crash has occurred\&. \fP"
.ti -1c
.RI "void \fBad_check_for_fire\fP (void)"
.br
.RI "\fIChecks for fire\&. \fP"
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "float \fBEXT_TEMPERATURE\fP"
.br
.ti -1c
.RI "float \fBEXT_TOTAL_ACCELERATION_AVG\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
\fBAuthor:\fP
.RS 4
Andi Degn 
.PP
Kenneth René Jensen 
.RE
.PP
\fBVersion:\fP
.RS 4
0\&.1 
.RE
.PP

.PP
Definition in file \fBaccident_detection\&.h\fP\&.
.SH "Variable Documentation"
.PP 
.SS "float EXT_TEMPERATURE"

.PP
Definition at line 14 of file accident_detection\&.c\&.
.SS "float EXT_TOTAL_ACCELERATION_AVG"

.PP
Definition at line 15 of file accident_detection\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for VROOM from the source code\&.
