.TH "D:/Dropbox/Skole Opgaver/ICT Engineering/7th Semester/Bachelor Project/Source Code/VROOM/VROOM_working/accident_logic/accident_data.h" 3 "Wed Dec 3 2014" "Version v0.01" "VROOM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/Dropbox/Skole Opgaver/ICT Engineering/7th Semester/Bachelor Project/Source Code/VROOM/VROOM_working/accident_logic/accident_data.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <avr/io\&.h>\fP
.br
\fC#include '\&.\&./vroom_config\&.h'\fP
.br
\fC#include '\&.\&./hardware_boards/sim908/at_commands\&.h'\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBpacked\fP"
.br
.RI "\fIstruct containing the MSD for an accident report \fP"
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBAD_FUEL_TYPE_OTHER\fP   0"
.br
.ti -1c
.RI "#define \fBAD_FUEL_TYPE_GASOLINE\fP   1"
.br
.ti -1c
.RI "#define \fBAD_FUEL_TYPE_DIESEL\fP   2"
.br
.ti -1c
.RI "#define \fBAD_FUEL_TYPE_NATURALGAS\fP   3"
.br
.ti -1c
.RI "#define \fBAD_FUEL_TYPE_PROPANE\fP   4"
.br
.ti -1c
.RI "#define \fBAD_FUEL_TYPE_ELECTRIC\fP   5"
.br
.ti -1c
.RI "#define \fBAD_FUEL_TYPE_HYDROGEN\fP   6"
.br
.ti -1c
.RI "#define \fBAD_VEHICLE_CLASS_L\fP(category)   (1<<4 | category)	/* Motor vehicles with less than four wheels */"
.br
.ti -1c
.RI "#define \fBAD_VEHICLE_CLASS_M\fP(category)   (2<<4 | category)	/* Power-driven vehicles having at least four wheels and used for the carriage of passengers */"
.br
.ti -1c
.RI "#define \fBAD_VEHICLE_CLASS_N\fP(category)   (3<<4 | category)	/* Power-driven vehicles having at least four wheels and used for the carriage of goods */"
.br
.ti -1c
.RI "#define \fBAD_VEHICLE_CLASS_O\fP(category)   (4<<4 | category)	/* Trailers (including semi–trailers) */"
.br
.ti -1c
.RI "#define \fBAD_VEHICLE_CLASS_T\fP(category)   (5<<4 | category)	/* Agricultural and Forestry tractors */"
.br
.ti -1c
.RI "#define \fBAD_VEHICLE_CLASS_G\fP(category)   (6<<4 | category)	/* Off-road vehicles */"
.br
.ti -1c
.RI "#define \fBAD_VEHICLE_CLASS_SA\fP(category)   (7<<4 | category)	/* Special purpose vehicles (e\&.g\&. Ambulance, Hearse, Armoured vehicle or Motor caravan)	*/"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef struct \fBpacked\fP \fBAD_MSD\fP"
.br
.RI "\fIstruct containing the MSD for an accident report \fP"
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBAD_EMERGENCY_FLAG\fP { \fBEMERGENCY_NO_ALARM\fP = 0, \fBEMERGENCY_MANUAL_ALARM\fP = 1, \fBEMERGENCY_AUTO_ALARM\fP = 2, \fBEMERGENCY_ALARM_SENT\fP = 3 }"
.br
.RI "\fIFlag to detect if an alarm has been triggered\&. \fP"
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBad_emergency_alarm\fP (void)"
.br
.RI "\fIFunction to call when an emergency alarm is triggered\&. \fP"
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "char \fBEXT_MSD_FILENAME\fP [24]"
.br
.ti -1c
.RI "\fBAD_MSD\fP \fBEXT_MSD\fP"
.br
.ti -1c
.RI "\fBAD_EMERGENCY_FLAG\fP \fBEXT_EMERGENCY_FLAG\fP"
.br
.ti -1c
.RI "\fBAT_CONNECTION_STATUS_FLAG\fP \fBEXT_CONNECTION_CREG_FLAG\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
\fBAuthor:\fP
.RS 4
Kenneth René Jensen 
.RE
.PP
\fBVersion:\fP
.RS 4
0\&.7 
.RE
.PP

.PP
Definition in file \fBaccident_data\&.h\fP\&.
.SH "Variable Documentation"
.PP 
.SS "\fBAT_CONNECTION_STATUS_FLAG\fP EXT_CONNECTION_CREG_FLAG"

.PP
Definition at line 17 of file accident_data\&.c\&.
.SS "\fBAD_EMERGENCY_FLAG\fP EXT_EMERGENCY_FLAG"

.PP
Definition at line 16 of file accident_data\&.c\&.
.SS "\fBAD_MSD\fP EXT_MSD"

.PP
Definition at line 15 of file accident_data\&.c\&.
.SS "char EXT_MSD_FILENAME[24]"

.PP
Definition at line 84 of file sim908\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for VROOM from the source code\&.
