.TH "D:/Dropbox/Skole Opgaver/ICT Engineering/7th Semester/Bachelor Project/Source Code/VROOM/VROOM_working/accident_logic/accident_data.c" 3 "Tue Dec 2 2014" "Version v0.01" "VROOM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/Dropbox/Skole Opgaver/ICT Engineering/7th Semester/Bachelor Project/Source Code/VROOM/VROOM_working/accident_logic/accident_data.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <stdlib\&.h>\fP
.br
\fC#include <string\&.h>\fP
.br
\fC#include <util/delay\&.h>\fP
.br
\fC#include 'accident_data\&.h'\fP
.br
\fC#include '\&.\&./hardware_boards/sim908/sim908\&.h'\fP
.br
\fC#include '\&.\&./util/timer/timer\&.h'\fP
.br
\fC#include 'accident_detection\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBBLANK_CHAR\fP   0x20	/**> Define for the space char ' ' */"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "static void \fB_set_control_byte\fP (bool __position_can_be_trusted, bool __test_call, bool __manual_alarm, bool __auto_alarm)"
.br
.RI "\fIfunction to set the control byte Control byte: | Automatic activation | Manual activation | Test call | Confidence in position |---Reserved--- |
.br
 Bit: | 7 | 6 | 5 | 4 | 3 | 2 | 1 | 0 |
.br
\fP"
.ti -1c
.RI "static void \fB_set_VIN\fP (const char *__VIN)"
.br
.RI "\fIfunction to set the vehicle identification number \fP"
.ti -1c
.RI "static void \fB_set_optional_data\fP ()"
.br
.RI "\fIfunction to set further data (e\&.g\&. crash information, number of passengers, temperature) \fP"
.ti -1c
.RI "void \fBad_emergency_alarm\fP (void)"
.br
.RI "\fIFunction to call when an emergency alarm is triggered\&. \fP"
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBAD_MSD\fP \fBEXT_MSD\fP"
.br
.ti -1c
.RI "\fBAD_EMERGENCY_FLAG\fP \fBEXT_EMERGENCY_FLAG\fP = \fBEMERGENCY_NO_ALARM\fP"
.br
.ti -1c
.RI "\fBAT_CONNECTION_STATUS_FLAG\fP \fBEXT_CONNECTION_CREG_FLAG\fP = \fBCREG_NOT_REG_NOT_SEARCHING\fP"
.br
.ti -1c
.RI "static bool \fB_confidence_in_position\fP"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define BLANK_CHAR   0x20	/**> Define for the space char ' ' */"

.PP
Definition at line 12 of file accident_data\&.c\&.
.SH "Variable Documentation"
.PP 
.SS "bool _confidence_in_position\fC [static]\fP"

.PP
Definition at line 20 of file accident_data\&.c\&.
.SS "\fBAT_CONNECTION_STATUS_FLAG\fP EXT_CONNECTION_CREG_FLAG = \fBCREG_NOT_REG_NOT_SEARCHING\fP"

.PP
Definition at line 17 of file accident_data\&.c\&.
.SS "\fBAD_EMERGENCY_FLAG\fP EXT_EMERGENCY_FLAG = \fBEMERGENCY_NO_ALARM\fP"

.PP
Definition at line 16 of file accident_data\&.c\&.
.SS "\fBAD_MSD\fP EXT_MSD"

.PP
Definition at line 15 of file accident_data\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for VROOM from the source code\&.
