.TH "Accident Logic" 3 "Thu Dec 11 2014" "Version v0.01" "VROOM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Accident Logic \- 
.SS "Modules"

.in +1c
.ti -1c
.RI "\fBAccident Data\fP"
.br
.RI "\fIThis is the data for an Accident report\&. \fP"
.ti -1c
.RI "\fBAccident Detection\fP"
.br
.RI "\fIThis file holds the logic for detecting an accident\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 

.SH "Author"
.PP 
Generated automatically by Doxygen for VROOM from the source code\&.
