.TH "Accident Data" 3 "Sun Nov 30 2014" "Version v0.01" "VROOM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Accident Data \- 
.SS "Modules"

.in +1c
.ti -1c
.RI "\fBPrivate\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBAD_FUEL_TYPE_OTHER\fP   0"
.br
.RI "\fIConstant vehicle fuel type definition\&. \fP"
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "struct \fB__attribute__\fP ((packed))"
.br
.RI "\fIstruct containing the MSD for an accident report \fP"
.in -1c
.SH "Detailed Description"
.PP 
This is the data for an Accident report\&. Comply eCall standards for MSD data structure\&. 
.PP
\fBNote:\fP
.RS 4
NOT YET Complies MISRO 2004 standards 
.RE
.PP

.SH "Macro Definition Documentation"
.PP 
.SS "#define AD_FUEL_TYPE_OTHER   0"

.PP
Constant vehicle fuel type definition\&. FUEL_TYPES 
.PP
Definition at line 45 of file accident_data\&.h\&.
.SH "Function Documentation"
.PP 
.SS "struct __attribute__ ((packed))"

.PP
struct containing the MSD for an accident report 
.PP
\fBNote:\fP
.RS 4
According eCall standard EN 15722 the MSD consists of 140 bytes 
.RE
.PP

.PP
Definition at line 25 of file accident_data\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for VROOM from the source code\&.
