.TH "Private" 3 "Sun Nov 30 2014" "Version v0.01" "VROOM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Private \- 
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBBLANK_CHAR\fP   0x20"
.br
.RI "\fIdefine for the space char ' ' \fP"
.in -1c
.SH "Detailed Description"
.PP 

.SH "Macro Definition Documentation"
.PP 
.SS "#define BLANK_CHAR   0x20"

.PP
define for the space char ' ' 
.PP
Definition at line 21 of file accident_data\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for VROOM from the source code\&.
