.TH "Public" 3 "Tue Dec 2 2014" "Version v0.01" "VROOM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Public \- 
.SS "Modules"

.in +1c
.ti -1c
.RI "\fBFule types\fP"
.br
.RI "\fIConstant vehicle fuel type definition\&. \fP"
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBad_emergency_alarm\fP (void)"
.br
.RI "\fIFunction to call when an emergency alarm is triggered\&. \fP"
.ti -1c
.RI "struct \fB__attribute__\fP ((packed))"
.br
.RI "\fIstruct containing the MSD for an accident report \fP"
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "char \fBEXT_MSD_FILENAME\fP [24]"
.br
.RI "\fIConstant vehicle class type definition\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 

.SH "Function Documentation"
.PP 
.SS "struct __attribute__ ((packed))"

.PP
struct containing the MSD for an accident report 
.PP
\fBNote:\fP
.RS 4
According eCall standard EN 15722 the MSD consists of 140 bytes 
.RE
.PP

.PP
.RS 4
Referring to a public register to determine the meaning and encoding of the optional data 
.RE
.PP
.PP
.RS 4
Numbers of re-transmission 
.RE
.PP
.PP
.RS 4
| bit 7: Automatic activation | bit 6: Manual activation | bit 5: Test call | bit 4: Confidence in position | bit 3-0: Reserved | 
.RE
.PP
.PP
.RS 4
| bit 7-4 = classification | bit 3-0: category | 
.RE
.PP
.PP
.RS 4
VIN number 17-characters (last 3 char is blank) ISO 3779 
.RE
.PP
.PP
.RS 4
UTC Seconds 
.RE
.PP
.PP
.RS 4
Latitude (WGS-84) in milliarcseconds (-324000000 ? value ? 324000000) ISO 6709 
.RE
.PP
.PP
.RS 4
Longitude (WGS-84) in milliarcseconds (-648000000 ? value ? 648000000) ISO 6709 
.RE
.PP
.PP
.RS 4
Direction in degrees\&. The nearest integer of 255\&.0*value/360\&.0 (0 <= value >= 255) 
.RE
.PP
.PP
.RS 4
Calculated size based on total MSD size - compulsory data 
.RE
.PP
.PP
.RS 4
Optional\&. Further data (e\&.g\&. crash information, number of passengers) or blank field 
.RE
.PP

.PP
Definition at line 28 of file accident_data\&.h\&.
.SS "void ad_emergency_alarm (void)"

.PP
Function to call when an emergency alarm is triggered\&. Starts the sequence required for placing an emergency call and send an MSD packet\&. Steps in function:
.br
.IP "1." 4
Record needed data
.br

.IP "2." 4
Create MSD structure
.br

.IP "3." 4
sent structure over FTP
.br

.IP "4." 4
call to emergency number
.PP
.PP
\fBParameters:\fP
.RS 4
\fIvoid\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
void 
.RE
.PP

.PP
.RS 4
M1 = No more than eight seats in addition to the driver’s seat, and having a maximum mass not exceeding 3\&.5 tons 
.RE
.PP

.PP
Definition at line 41 of file accident_data\&.c\&.
.SH "Variable Documentation"
.PP 
.SS "char EXT_MSD_FILENAME[24]"

.PP
Constant vehicle class type definition\&. 
.PP
\fBNote:\fP
.RS 4
Upper nibble contains class definition: [SA, L, M, N, O, T, G] @ Lower nibble contains class category definition: [1 - 7] @ Details: http://eur-lex.europa.eu/legal-content/EN/TXT/PDF/?uri=CELEX:32007L0046&from=EN 
.PP
.nf
                                                                          /
#define AD_VEHICLE_CLASS_L(category)    (1<<4 | category)   /* Motor vehicles with less than four wheels */
#define AD_VEHICLE_CLASS_M(category)    (2<<4 | category)   /* Power-driven vehicles having at least four wheels and used for the carriage of passengers */
#define AD_VEHICLE_CLASS_N(category)    (3<<4 | category)   /* Power-driven vehicles having at least four wheels and used for the carriage of goods */
#define AD_VEHICLE_CLASS_O(category)    (4<<4 | category)   /* Trailers (including semi–trailers) */
#define AD_VEHICLE_CLASS_T(category)    (5<<4 | category)   /* Agricultural and Forestry tractors */
#define AD_VEHICLE_CLASS_G(category)    (6<<4 | category)   /* Off-road vehicles */
#define AD_VEHICLE_CLASS_SA(category)   (7<<4 | category)   /* Special purpose vehicles (e\&.g\&. Ambulance, Hearse, Armoured vehicle or Motor caravan) */

.fi
.PP
.RE
.PP
Flag to detect if an alarm has been triggered 
.PP
.nf
                                                                          /
typedef enum {  EMERGENCY_NO_ALARM = 0,
                EMERGENCY_MANUAL_ALARM = 1,
                EMERGENCY_AUTO_ALARM = 2,
                EMERGENCY_ALARM_SENT = 3
} AD_EMERGENCY_FLAG;

.fi
.PP
 
.PP
Definition at line 47 of file sim908\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for VROOM from the source code\&.
