.TH "Accident detection parameters" 3 "Tue Dec 2 2014" "Version v0.01" "VROOM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Accident detection parameters \- 
.PP
Parameters for detecting an accident\&.  
Parameters for detecting an accident\&. 


.SH "Author"
.PP 
Generated automatically by Doxygen for VROOM from the source code\&.
