.TH "AT Commands" 3 "Thu Dec 11 2014" "Version v0.01" "VROOM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AT Commands \- 
.PP
This is a header containing all the most relevant AT commands for this system\&.  

.SS "Modules"

.in +1c
.ti -1c
.RI "\fBConnection type\fP"
.br
.RI "\fIDefines for the Data carrier type\&. \fP"
.ti -1c
.RI "\fBDiag\fP"
.br
.RI "\fIDefines for the diagnostics\&. \fP"
.ti -1c
.RI "\fBCREG enable\fP"
.br
.RI "\fIDefine for the enable +CREG: unsolicited result code\&. \fP"
.ti -1c
.RI "\fBBaud rate\fP"
.br
.RI "\fIDefines for the baud rate\&. \fP"
.ti -1c
.RI "\fBFunctionality\fP"
.br
.RI "\fIDefines for the phone functionality\&. \fP"
.ti -1c
.RI "\fBCall allowance\fP"
.br
.RI "\fIDefines for the incoming call allowance setting\&. \fP"
.ti -1c
.RI "\fBWhite list (emergency number)\fP"
.br
.RI "\fIDefine for the calls white list\&. \fP"
.ti -1c
.RI "\fBFlow control\fP"
.br
.RI "\fIDefines for the flow control\&. \fP"
.ti -1c
.RI "\fBProfile\fP"
.br
.RI "\fIDefines for profile management\&. \fP"
.ti -1c
.RI "\fBPDP context\fP"
.br
.RI "\fIDefines GPRS PDP context\&. \fP"
.ti -1c
.RI "\fBFTP communication\fP"
.br
.RI "\fIDefines FTP setup and communication\&. \fP"
.ti -1c
.RI "\fBModule status\fP"
.br
.RI "\fIDefine for the module device status The different responses are:
.br
0 ready
.br
1 unavailable
.br
2 unknown
.br
3 ringing
.br
4 call in progress
.br
5 asleep
.br
\&. \fP"
.ti -1c
.RI "\fBCall\fP"
.br
.RI "\fIDefines for the call\&. \fP"
.ti -1c
.RI "\fBMessages\fP"
.br
.RI "\fIDefines for the message\&. \fP"
.ti -1c
.RI "\fBAudio\fP"
.br
.RI "\fIDefines for the audio setup\&. \fP"
.ti -1c
.RI "\fBConnection\fP"
.br
.RI "\fIDefines for the connection\&. \fP"
.ti -1c
.RI "\fBGPS\fP"
.br
.RI "\fIDefines for the GPS\&. \fP"
.ti -1c
.RI "\fBCtrl+Z\fP"
.br
.RI "\fIDefine for the ctrl+Z command\&. \fP"
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBAT_CONNECTION_STATUS_FLAG\fP { \fBCREG_NOT_REG_NOT_SEARCHING\fP = 0U, \fBCREG_REGISTERED_HOME_NETWORK\fP = 1U, \fBCREG_NOT_REG_SEARCHING\fP = 2U, \fBCREG_REGISTRATION_DENIED\fP = 3U, \fBCREG_UNKNOWN\fP = 4U, \fBCREG_REGISTERED_ROAMING\fP = 5U }"
.br
.RI "\fIFlag to detect the connection status\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
This is a header containing all the most relevant AT commands for this system\&. 


.PP
\fBNote:\fP
.RS 4
Complies MISRA 2004 standards 
.RE
.PP

.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBAT_CONNECTION_STATUS_FLAG\fP"

.PP
Flag to detect the connection status\&. 
.PP
\fBNote:\fP
.RS 4
Corresponding to CREG response in SIM908 p\&. 77 in AT Commands manual v\&. 1\&.02 
.RE
.PP

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fICREG_NOT_REG_NOT_SEARCHING \fP\fP
.TP
\fB\fICREG_REGISTERED_HOME_NETWORK \fP\fP
.TP
\fB\fICREG_NOT_REG_SEARCHING \fP\fP
.TP
\fB\fICREG_REGISTRATION_DENIED \fP\fP
.TP
\fB\fICREG_UNKNOWN \fP\fP
.TP
\fB\fICREG_REGISTERED_ROAMING \fP\fP
.PP
Definition at line 25 of file at_commands\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for VROOM from the source code\&.
