.TH "Baud rate" 3 "Wed Dec 3 2014" "Version v0.01" "VROOM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Baud rate \- 
.PP
Defines for the baud rate\&.  

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBAT_BAUD_AUTO\fP   'AT+IPR=0'"
.br
.ti -1c
.RI "#define \fBAT_BAUD_1200\fP   'AT+IPR=1200'"
.br
.ti -1c
.RI "#define \fBAT_BAUD_2400\fP   'AT+IPR=2400'"
.br
.ti -1c
.RI "#define \fBAT_BAUD_4800\fP   'AT+IPR=4800'"
.br
.ti -1c
.RI "#define \fBAT_BAUD_9600\fP   'AT+IPR=9600'"
.br
.ti -1c
.RI "#define \fBAT_BAUD_19K2\fP   'AT+IPR=19200'"
.br
.ti -1c
.RI "#define \fBAT_BAUD_38K4\fP   'AT+IPR=38400'"
.br
.ti -1c
.RI "#define \fBAT_BAUD_57K6\fP   'AT+IPR=57600'"
.br
.ti -1c
.RI "#define \fBAT_BAUD_115K2\fP   'AT+IPR=115200'"
.br
.in -1c
.SH "Detailed Description"
.PP 
Defines for the baud rate\&. 


.PP
\fBNote:\fP
.RS 4
autobauding does not support 115200bps 
.RE
.PP

.SH "Macro Definition Documentation"
.PP 
.SS "#define AT_BAUD_115K2   'AT+IPR=115200'"

.PP
Definition at line 81 of file at_commands\&.h\&.
.SS "#define AT_BAUD_1200   'AT+IPR=1200'"

.PP
Definition at line 74 of file at_commands\&.h\&.
.SS "#define AT_BAUD_19K2   'AT+IPR=19200'"

.PP
Definition at line 78 of file at_commands\&.h\&.
.SS "#define AT_BAUD_2400   'AT+IPR=2400'"

.PP
Definition at line 75 of file at_commands\&.h\&.
.SS "#define AT_BAUD_38K4   'AT+IPR=38400'"

.PP
Definition at line 79 of file at_commands\&.h\&.
.SS "#define AT_BAUD_4800   'AT+IPR=4800'"

.PP
Definition at line 76 of file at_commands\&.h\&.
.SS "#define AT_BAUD_57K6   'AT+IPR=57600'"

.PP
Definition at line 80 of file at_commands\&.h\&.
.SS "#define AT_BAUD_9600   'AT+IPR=9600'"

.PP
Definition at line 77 of file at_commands\&.h\&.
.SS "#define AT_BAUD_AUTO   'AT+IPR=0'"

.PP
Definition at line 73 of file at_commands\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for VROOM from the source code\&.
