.TH "Connection" 3 "Tue Dec 2 2014" "Version v0.01" "VROOM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Connection \- 
.PP
Defines for the connection\&.  

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBAT_CONN_SIGNAL_STRENGTH\fP   'AT+CSQ'"
.br
.ti -1c
.RI "#define \fBAT_CONN_ATTACH_STATUS\fP   'AT+CGATT?'"
.br
.ti -1c
.RI "#define \fBAT_CONN_NETWORK_REGISTRATION_STATUS\fP   'AT+CREG?'"
.br
.in -1c
.SH "Detailed Description"
.PP 
Defines for the connection\&. 


.SH "Macro Definition Documentation"
.PP 
.SS "#define AT_CONN_ATTACH_STATUS   'AT+CGATT?'"

.PP
Definition at line 245 of file at_commands\&.h\&.
.SS "#define AT_CONN_NETWORK_REGISTRATION_STATUS   'AT+CREG?'"

.PP
Definition at line 246 of file at_commands\&.h\&.
.SS "#define AT_CONN_SIGNAL_STRENGTH   'AT+CSQ'"

.PP
Definition at line 244 of file at_commands\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for VROOM from the source code\&.
