.TH "CREG enable" 3 "Thu Dec 11 2014" "Version v0.01" "VROOM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CREG enable \- 
.PP
Define for the enable +CREG: unsolicited result code\&.  

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBAT_ENABLE_CREG\fP   'AT+CREG=1'"
.br
.in -1c
.SH "Detailed Description"
.PP 
Define for the enable +CREG: unsolicited result code\&. 


.SH "Macro Definition Documentation"
.PP 
.SS "#define AT_ENABLE_CREG   'AT+CREG=1'"

.PP
Definition at line 64 of file at_commands\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for VROOM from the source code\&.
