.TH "Ctrl+Z" 3 "Wed Dec 3 2014" "Version v0.01" "VROOM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ctrl+Z \- 
.PP
Define for the ctrl+Z command\&.  

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBAT_CTRL_Z\fP   26"
.br
.in -1c
.SH "Detailed Description"
.PP 
Define for the ctrl+Z command\&. 


.SH "Macro Definition Documentation"
.PP 
.SS "#define AT_CTRL_Z   26"

.PP
Definition at line 272 of file at_commands\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for VROOM from the source code\&.
