.TH "Call" 3 "Tue Dec 2 2014" "Version v0.01" "VROOM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Call \- 
.PP
Defines for the call\&.  

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBAT_CALL_ANSWER\fP   'ATA'"
.br
.ti -1c
.RI "#define \fBAT_CALL_HANG_UP\fP   'ATH0'"
.br
.ti -1c
.RI "#define \fBAT_CALL_DIAL\fP(NUMBER)   'ATD' NUMBER ';'"
.br
.ti -1c
.RI "#define \fBAT_CALL_REDIAL\fP   'ATDL'"
.br
.ti -1c
.RI "#define \fBAT_CALL_SHOW_NUM\fP   'AT+CNUM'"
.br
.in -1c
.SH "Detailed Description"
.PP 
Defines for the call\&. 


.SH "Macro Definition Documentation"
.PP 
.SS "#define AT_CALL_ANSWER   'ATA'"

.PP
Definition at line 205 of file at_commands\&.h\&.
.SS "#define AT_CALL_DIAL(NUMBER)   'ATD' NUMBER ';'"

.PP
Definition at line 207 of file at_commands\&.h\&.
.SS "#define AT_CALL_HANG_UP   'ATH0'"

.PP
Definition at line 206 of file at_commands\&.h\&.
.SS "#define AT_CALL_REDIAL   'ATDL'"

.PP
Definition at line 208 of file at_commands\&.h\&.
.SS "#define AT_CALL_SHOW_NUM   'AT+CNUM'"

.PP
Definition at line 209 of file at_commands\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for VROOM from the source code\&.
