.TH "Diag" 3 "Wed Dec 3 2014" "Version v0.01" "VROOM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Diag \- 
.PP
Defines for the diagnostics\&.  

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBAT_DIAG_TEST\fP   'AT'"
.br
.ti -1c
.RI "#define \fBAT_DIAG_ECHO_ENABLE\fP   'ATE1'"
.br
.ti -1c
.RI "#define \fBAT_DIAG_ECHO_DISABLE\fP   'ATE0'"
.br
.ti -1c
.RI "#define \fBAT_DIAG_AUTO_ANSWER\fP(NO_OF_RINGS)   'ATS0=' NO_OF_RINGS"
.br
.ti -1c
.RI "#define \fBAT_DIAG_MODEL_NO\fP   'AT+CGMM'"
.br
.ti -1c
.RI "#define \fBAT_DIAG_MANUFACTURER\fP   'AT+CGMI'"
.br
.in -1c
.SH "Detailed Description"
.PP 
Defines for the diagnostics\&. 


.SH "Macro Definition Documentation"
.PP 
.SS "#define AT_DIAG_AUTO_ANSWER(NO_OF_RINGS)   'ATS0=' NO_OF_RINGS"

.PP
Definition at line 52 of file at_commands\&.h\&.
.SS "#define AT_DIAG_ECHO_DISABLE   'ATE0'"

.PP
Definition at line 51 of file at_commands\&.h\&.
.SS "#define AT_DIAG_ECHO_ENABLE   'ATE1'"

.PP
Definition at line 50 of file at_commands\&.h\&.
.SS "#define AT_DIAG_MANUFACTURER   'AT+CGMI'"

.PP
Definition at line 54 of file at_commands\&.h\&.
.SS "#define AT_DIAG_MODEL_NO   'AT+CGMM'"

.PP
Definition at line 53 of file at_commands\&.h\&.
.SS "#define AT_DIAG_TEST   'AT'"

.PP
Definition at line 49 of file at_commands\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for VROOM from the source code\&.
