.TH "Functionality" 3 "Wed Dec 3 2014" "Version v0.01" "VROOM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Functionality \- 
.PP
Defines for the phone functionality\&.  

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBAT_MINIMUM_FUNCTIONALITY\fP   'AT+CFUN=0'"
.br
.ti -1c
.RI "#define \fBAT_FULL_FUNCTIONALITY\fP   'AT+CFUN=1'"
.br
.ti -1c
.RI "#define \fBAT_DISABLE_TX_RX\fP   'AT+CFUN=4'"
.br
.ti -1c
.RI "#define \fBAT_RESET_MODULE\fP   'AT+CFUN=1,1'"
.br
.ti -1c
.RI "#define \fBAT_ENTER_SIM_PIN\fP(\fBPIN\fP)   'AT+CPIN=' PIN"
.br
.in -1c
.SH "Detailed Description"
.PP 
Defines for the phone functionality\&. 


.SH "Macro Definition Documentation"
.PP 
.SS "#define AT_DISABLE_TX_RX   'AT+CFUN=4'"

.PP
Definition at line 92 of file at_commands\&.h\&.
.SS "#define AT_ENTER_SIM_PIN(\fBPIN\fP)   'AT+CPIN=' PIN"

.PP
Definition at line 94 of file at_commands\&.h\&.
.SS "#define AT_FULL_FUNCTIONALITY   'AT+CFUN=1'"

.PP
Definition at line 91 of file at_commands\&.h\&.
.SS "#define AT_MINIMUM_FUNCTIONALITY   'AT+CFUN=0'"

.PP
Definition at line 90 of file at_commands\&.h\&.
.SS "#define AT_RESET_MODULE   'AT+CFUN=1,1'"

.PP
Definition at line 93 of file at_commands\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for VROOM from the source code\&.
