.TH "Flow control" 3 "Tue Dec 2 2014" "Version v0.01" "VROOM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Flow control \- 
.PP
Defines for the flow control\&.  

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBAT_NO_FLOW_CONTROL\fP   'AT+IFC=0,0'"
.br
.ti -1c
.RI "#define \fBAT_SOFTWARE_FLOW_CONTROL\fP   'AT+IFC=1,1' /* Should not be used for data calls */"
.br
.ti -1c
.RI "#define \fBAT_HARDWARE_FLOW_CONTROL\fP   'AT+IFC=2,2'"
.br
.in -1c
.SH "Detailed Description"
.PP 
Defines for the flow control\&. 


.SH "Macro Definition Documentation"
.PP 
.SS "#define AT_HARDWARE_FLOW_CONTROL   'AT+IFC=2,2'"

.PP
Definition at line 124 of file at_commands\&.h\&.
.SS "#define AT_NO_FLOW_CONTROL   'AT+IFC=0,0'"

.PP
Definition at line 122 of file at_commands\&.h\&.
.SS "#define AT_SOFTWARE_FLOW_CONTROL   'AT+IFC=1,1' /* Should not be used for data calls */"

.PP
Definition at line 123 of file at_commands\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for VROOM from the source code\&.
