.TH "Messages" 3 "Thu Dec 11 2014" "Version v0.01" "VROOM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Messages \- 
.PP
Defines for the message\&.  

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBAT_MSG_READ\fP   'AT+CMGR=' /* Add number in end to select msg to read */"
.br
.ti -1c
.RI "#define \fBAT_MSG_DEL_ALL\fP   'AT+CMGD=1,4'"
.br
.ti -1c
.RI "#define \fBAT_MSG_FORMAT\fP   'AT+CMGF=' /* Add number */"
.br
.ti -1c
.RI "#define \fBAT_MSG_SEND\fP   'AT+CMGS\\''"
.br
.in -1c
.SH "Detailed Description"
.PP 
Defines for the message\&. 


.SH "Macro Definition Documentation"
.PP 
.SS "#define AT_MSG_DEL_ALL   'AT+CMGD=1,4'"

.PP
Definition at line 221 of file at_commands\&.h\&.
.SS "#define AT_MSG_FORMAT   'AT+CMGF=' /* Add number */"

.PP
Definition at line 222 of file at_commands\&.h\&.
.SS "#define AT_MSG_READ   'AT+CMGR=' /* Add number in end to select msg to read */"

.PP
Definition at line 220 of file at_commands\&.h\&.
.SS "#define AT_MSG_SEND   'AT+CMGS\\''"

.PP
Definition at line 223 of file at_commands\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for VROOM from the source code\&.
