.TH "PDP context" 3 "Thu Dec 11 2014" "Version v0.01" "VROOM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PDP context \- 
.PP
Defines GPRS PDP context\&.  

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBAT_GPRS_PDP_ACTIVATE_CONTEXT\fP   'AT+CGACT=1,1'"
.br
.ti -1c
.RI "#define \fBAT_GPRS_PDP_GET_IP\fP   'AT+CGPADDR=1'"
.br
.ti -1c
.RI "#define \fBAT_GPRS_PDP_SETUP_CONTEXT\fP(APN)   'AT+CGDCONT=1,\\'IP\\',\\'' APN '\\''"
.br
.in -1c
.SH "Detailed Description"
.PP 
Defines GPRS PDP context\&. 


.SH "Macro Definition Documentation"
.PP 
.SS "#define AT_GPRS_PDP_ACTIVATE_CONTEXT   'AT+CGACT=1,1'"

.PP
Definition at line 148 of file at_commands\&.h\&.
.SS "#define AT_GPRS_PDP_GET_IP   'AT+CGPADDR=1'"

.PP
Definition at line 149 of file at_commands\&.h\&.
.SS "#define AT_GPRS_PDP_SETUP_CONTEXT(APN)   'AT+CGDCONT=1,\\'IP\\',\\'' APN '\\''"

.PP
Definition at line 150 of file at_commands\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for VROOM from the source code\&.
