.TH "Profile" 3 "Thu Dec 11 2014" "Version v0.01" "VROOM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Profile \- 
.PP
Defines for profile management\&.  

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBAT_STORE_PROFILE0\fP   'AT&W0'"
.br
.ti -1c
.RI "#define \fBAT_STORE_PROFILE1\fP   'AT&W1'"
.br
.ti -1c
.RI "#define \fBAT_RESTORE_PROFILE0\fP   'ATZ0'"
.br
.ti -1c
.RI "#define \fBAT_RESTORE_PROFILE1\fP   'ATZ1'"
.br
.ti -1c
.RI "#define \fBAT_MANUFACTURER_DEFAULTS\fP   'AT&F0'"
.br
.in -1c
.SH "Detailed Description"
.PP 
Defines for profile management\&. 


.SH "Macro Definition Documentation"
.PP 
.SS "#define AT_MANUFACTURER_DEFAULTS   'AT&F0'"

.PP
Definition at line 139 of file at_commands\&.h\&.
.SS "#define AT_RESTORE_PROFILE0   'ATZ0'"

.PP
Definition at line 137 of file at_commands\&.h\&.
.SS "#define AT_RESTORE_PROFILE1   'ATZ1'"

.PP
Definition at line 138 of file at_commands\&.h\&.
.SS "#define AT_STORE_PROFILE0   'AT&W0'"

.PP
Definition at line 135 of file at_commands\&.h\&.
.SS "#define AT_STORE_PROFILE1   'AT&W1'"

.PP
Definition at line 136 of file at_commands\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for VROOM from the source code\&.
