.TH "Module status" 3 "Tue Dec 2 2014" "Version v0.01" "VROOM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Module status \- 
.PP
Define for the module device status The different responses are:
.br
0 ready
.br
1 unavailable
.br
2 unknown
.br
3 ringing
.br
4 call in progress
.br
5 asleep
.br
\&.  

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBAT_MODULE_DEVICE_STATUS\fP   'AT+CPAS'"
.br
.in -1c
.SH "Detailed Description"
.PP 
Define for the module device status The different responses are:
.br
0 ready
.br
1 unavailable
.br
2 unknown
.br
3 ringing
.br
4 call in progress
.br
5 asleep
.br
\&. 


.SH "Macro Definition Documentation"
.PP 
.SS "#define AT_MODULE_DEVICE_STATUS   'AT+CPAS'"

.PP
Definition at line 196 of file at_commands\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for VROOM from the source code\&.
