.TH "White list (emergency number)" 3 "Wed Dec 3 2014" "Version v0.01" "VROOM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
White list (emergency number) \- 
.PP
Define for the calls white list\&.  

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBAT_EMERGENCY_CALL_ONLY\fP(NUMBER)   'AT+CWHITELIST=1,1,' NUMBER"
.br
.in -1c
.SH "Detailed Description"
.PP 
Define for the calls white list\&. 


.SH "Macro Definition Documentation"
.PP 
.SS "#define AT_EMERGENCY_CALL_ONLY(NUMBER)   'AT+CWHITELIST=1,1,' NUMBER"

.PP
Definition at line 114 of file at_commands\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for VROOM from the source code\&.
