.TH "D:/Dropbox/Skole Opgaver/ICT Engineering/7th Semester/Bachelor Project/Source Code/VROOM/VROOM_working/hardware_boards/lcd_board/button_led/btn_led_lcd.c" 3 "Tue Dec 2 2014" "Version v0.01" "VROOM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/Dropbox/Skole Opgaver/ICT Engineering/7th Semester/Bachelor Project/Source Code/VROOM/VROOM_working/hardware_boards/lcd_board/button_led/btn_led_lcd.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'btn_led_lcd\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBDDR\fP(x)   (*(&x - 1))"
.br
.ti -1c
.RI "#define \fBPIN\fP(x)   ( &PORTF==&(x) ? _SFR_IO8(0x00) : (*(&x - 2)) )"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBbtn_led_lcd_init\fP ()"
.br
.ti -1c
.RI "bool \fBbtn_lcd_is_pressed\fP (uint8_t pin)"
.br
.ti -1c
.RI "void \fBled_lcd_set\fP (uint8_t led, uint8_t state)"
.br
.ti -1c
.RI "void \fBled_lcd_toggle\fP (uint8_t led)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define DDR(x)   (*(&x - 1))"

.PP
Definition at line 10 of file btn_led_lcd\&.c\&.
.SS "#define PIN(x)   ( &PORTF==&(x) ? _SFR_IO8(0x00) : (*(&x - 2)) )"

.PP
Definition at line 11 of file btn_led_lcd\&.c\&.
.SH "Function Documentation"
.PP 
.SS "bool btn_lcd_is_pressed (uint8_tpin)"

.PP
Definition at line 22 of file btn_led_lcd\&.c\&.
.SS "void btn_led_lcd_init (void)"

.PP
Definition at line 13 of file btn_led_lcd\&.c\&.
.SS "void led_lcd_set (uint8_tled, uint8_tstate)"

.PP
Definition at line 26 of file btn_led_lcd\&.c\&.
.SS "void led_lcd_toggle (uint8_tled)"

.PP
Definition at line 36 of file btn_led_lcd\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for VROOM from the source code\&.
