.TH "D:/Dropbox/Skole Opgaver/ICT Engineering/7th Semester/Bachelor Project/Source Code/VROOM/VROOM_working/hardware_boards/car_panel/car_panel.c" 3 "Thu Dec 11 2014" "Version v0.01" "VROOM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/Dropbox/Skole Opgaver/ICT Engineering/7th Semester/Bachelor Project/Source Code/VROOM/VROOM_working/hardware_boards/car_panel/car_panel.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <avr/interrupt\&.h>\fP
.br
\fC#include <util/delay\&.h>\fP
.br
\fC#include 'car_panel\&.h'\fP
.br
\fC#include '\&.\&./\&.\&./accident_logic/accident_data\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBPORT\fP   \fBCONFIG_PORT_CAR_PANEL\fP"
.br
.ti -1c
.RI "#define \fBDDR\fP(x)   (*(&x - 1))"
.br
.ti -1c
.RI "#define \fBPIN\fP(x)   (*(&x - 2))"
.br
.ti -1c
.RI "#define \fBBTN_CANCEL\fP   0"
.br
.ti -1c
.RI "#define \fBBTN_ALARM\fP   1"
.br
.ti -1c
.RI "#define \fBLED_CONTROL\fP   3"
.br
.ti -1c
.RI "#define \fBLED_STATUS_RED\fP   5"
.br
.ti -1c
.RI "#define \fBLED_STATUS_BLUE\fP   6"
.br
.ti -1c
.RI "#define \fBLED_STATUS_GREEN\fP   7"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBcar_panel_init\fP (void)"
.br
.RI "\fIInitiates the Car Panel\&. \fP"
.ti -1c
.RI "void \fBcar_panel_start\fP (void)"
.br
.RI "\fIEnable external interrupt on ALARM button PJ1 (PCINT10) \fP"
.ti -1c
.RI "void \fBcar_panel_set_status\fP (\fBStatus\fP __s)"
.br
.RI "\fISet the status LED\&. \fP"
.ti -1c
.RI "void \fBcar_panel_set_control\fP (\fBControl\fP __c)"
.br
.RI "\fISet the control LED\&. \fP"
.ti -1c
.RI "bool \fBcar_panel_wait_cancel_emmergency\fP (void)"
.br
.RI "\fIUses nested while loops to create a waiting period and then check if the cancel alarm button is pressed and held for at least 3 seconds\&. \fP"
.ti -1c
.RI "void \fBcar_panel_set_alarm_button_state\fP (bool state)"
.br
.RI "\fISets the activation state of the alarm button\&. \fP"
.ti -1c
.RI "void \fBcar_panel_set_cancel_button_state\fP (bool state)"
.br
.RI "\fISets the activation state of the cancel button\&. \fP"
.ti -1c
.RI "\fBISR\fP (PCINT1_vect, ISR_NOBLOCK)"
.br
.RI "\fIISR for ALARM button When triggered the port pin is determined and based on which pin, if it is the pin where the ALARM button is located, a timed loop is entered to check if the button is pressed and held for at least 3 seconds\&. If it is, the cancel button check is called, if not, return\&. \fP"
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "static uint8_t \fB_car_panel_counter\fP"
.br
.ti -1c
.RI "static bool \fB_alarm_cancelled\fP"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "bool _alarm_cancelled\fC [static]\fP"

.PP
Definition at line 46 of file car_panel\&.c\&.
.SS "uint8_t _car_panel_counter\fC [static]\fP"

.PP
Definition at line 45 of file car_panel\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for VROOM from the source code\&.
