.TH "Button press time" 3 "Tue Dec 2 2014" "Version v0.01" "VROOM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Button press time \- 
.PP
Defines for the time of button press before activation/deactivation in 1/10 sec\&.  

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBBUTTON_PRESS_TIME\fP   30"
.br
.in -1c
.SH "Detailed Description"
.PP 
Defines for the time of button press before activation/deactivation in 1/10 sec\&. 


.SH "Macro Definition Documentation"
.PP 
.SS "#define BUTTON_PRESS_TIME   30"

.PP
Definition at line 27 of file car_panel\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for VROOM from the source code\&.
