.TH "Mask bits" 3 "Wed Dec 3 2014" "Version v0.01" "VROOM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Mask bits \- 
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBBTN_CANCEL\fP   0"
.br
.ti -1c
.RI "#define \fBBTN_ALARM\fP   1"
.br
.ti -1c
.RI "#define \fBLED_CONTROL\fP   3"
.br
.ti -1c
.RI "#define \fBLED_STATUS_RED\fP   5"
.br
.ti -1c
.RI "#define \fBLED_STATUS_BLUE\fP   6"
.br
.ti -1c
.RI "#define \fBLED_STATUS_GREEN\fP   7"
.br
.in -1c
.SH "Detailed Description"
.PP 
Defines for the different mask bits 
.SH "Macro Definition Documentation"
.PP 
.SS "#define BTN_ALARM   1"

.PP
Definition at line 38 of file car_panel\&.c\&.
.SS "#define BTN_CANCEL   0"

.PP
Definition at line 37 of file car_panel\&.c\&.
.SS "#define LED_CONTROL   3"

.PP
Definition at line 39 of file car_panel\&.c\&.
.SS "#define LED_STATUS_BLUE   6"

.PP
Definition at line 41 of file car_panel\&.c\&.
.SS "#define LED_STATUS_GREEN   7"

.PP
Definition at line 42 of file car_panel\&.c\&.
.SS "#define LED_STATUS_RED   5"

.PP
Definition at line 40 of file car_panel\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for VROOM from the source code\&.
