.TH "Public" 3 "Thu Dec 11 2014" "Version v0.01" "VROOM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Public \- 
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBStatus\fP { \fBSTATUS_BLUE_TOGGLE\fP, \fBSTATUS_BLUE\fP, \fBSTATUS_RED\fP, \fBSTATUS_GREEN\fP, \fBSTATUS_RESET\fP }"
.br
.RI "\fIDefines the state of status LED\&. \fP"
.ti -1c
.RI "enum \fBControl\fP { \fBALARM_WAITING\fP, \fBALARM_ACTIVATED\fP, \fBALARM_NOT_ACTIVATED\fP }"
.br
.RI "\fIDefines the state of control LED\&. \fP"
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBcar_panel_init\fP (void)"
.br
.RI "\fIInitiates the Car Panel\&. \fP"
.ti -1c
.RI "void \fBcar_panel_start\fP (void)"
.br
.RI "\fIEnable external interrupt on ALARM button PJ1 (PCINT10) \fP"
.ti -1c
.RI "void \fBcar_panel_set_status\fP (\fBStatus\fP __s)"
.br
.RI "\fISet the status LED\&. \fP"
.ti -1c
.RI "void \fBcar_panel_set_control\fP (\fBControl\fP __c)"
.br
.RI "\fISet the control LED\&. \fP"
.ti -1c
.RI "bool \fBcar_panel_wait_cancel_emmergency\fP (void)"
.br
.RI "\fIUses nested while loops to create a waiting period and then check if the cancel alarm button is pressed and held for at least 3 seconds\&. \fP"
.ti -1c
.RI "void \fBcar_panel_set_alarm_button_state\fP (bool state)"
.br
.RI "\fISets the activation state of the alarm button\&. \fP"
.ti -1c
.RI "void \fBcar_panel_set_cancel_button_state\fP (bool state)"
.br
.RI "\fISets the activation state of the cancel button\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 

.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBControl\fP"

.PP
Defines the state of control LED\&. 
.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIALARM_WAITING \fP\fP
.TP
\fB\fIALARM_ACTIVATED \fP\fP
.TP
\fB\fIALARM_NOT_ACTIVATED \fP\fP
.PP
Definition at line 38 of file car_panel\&.h\&.
.SS "enum \fBStatus\fP"

.PP
Defines the state of status LED\&. 
.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fISTATUS_BLUE_TOGGLE \fP\fP
.TP
\fB\fISTATUS_BLUE \fP\fP
.TP
\fB\fISTATUS_RED \fP\fP
.TP
\fB\fISTATUS_GREEN \fP\fP
.TP
\fB\fISTATUS_RESET \fP\fP
.PP
Definition at line 25 of file car_panel\&.h\&.
.SH "Function Documentation"
.PP 
.SS "void car_panel_init (void)"

.PP
Initiates the Car Panel\&. Sets up the ports and sets the panel status to STATUS_OFFLINE
.PP
\fBParameters:\fP
.RS 4
\fIvoid\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
void 
.RE
.PP

.PP
Definition at line 52 of file car_panel\&.c\&.
.SS "void car_panel_set_alarm_button_state (boolstate)"

.PP
Sets the activation state of the alarm button\&. Sets the interrupt for the alarm button
.PP
\fBParameters:\fP
.RS 4
\fIbool\fP state - true = activate; false = de-activate
.RE
.PP
\fBReturns:\fP
.RS 4
void 
.RE
.PP

.PP
Definition at line 195 of file car_panel\&.c\&.
.SS "void car_panel_set_cancel_button_state (boolstate)"

.PP
Sets the activation state of the cancel button\&. Sets the interrupt for the cancel button
.PP
\fBParameters:\fP
.RS 4
\fIbool\fP state - true = activate; false = de-activate
.RE
.PP
\fBReturns:\fP
.RS 4
void 
.RE
.PP

.PP
Definition at line 208 of file car_panel\&.c\&.
.SS "void car_panel_set_control (\fBControl\fP__c)"

.PP
Set the control LED\&. Sets the alarm led's to the status of __c
.PP
\fBParameters:\fP
.RS 4
\fIControl\fP __c - control of the panel\&. See Control define
.RE
.PP
\fBReturns:\fP
.RS 4
void 
.RE
.PP

.PP
Definition at line 122 of file car_panel\&.c\&.
.SS "void car_panel_set_status (\fBStatus\fP__s)"

.PP
Set the status LED\&. Sets the 3-colour led's state to the status of __s
.PP
\fBParameters:\fP
.RS 4
\fIStatus\fP __s - status of the panel\&. See Status define
.RE
.PP
\fBReturns:\fP
.RS 4
void 
.RE
.PP

.PP
Definition at line 86 of file car_panel\&.c\&.
.SS "void car_panel_start (void)"

.PP
Enable external interrupt on ALARM button PJ1 (PCINT10) Sets the interrupt registers for the pin
.PP
\fBParameters:\fP
.RS 4
\fIvoid\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
void 
.RE
.PP

.PP
Definition at line 75 of file car_panel\&.c\&.
.SS "bool car_panel_wait_cancel_emmergency (void)"

.PP
Uses nested while loops to create a waiting period and then check if the cancel alarm button is pressed and held for at least 3 seconds\&. Cancel alarm button\&. Wait 3 seconds to determine false alarm\&.
.PP
\fBParameters:\fP
.RS 4
\fIvoid\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
bool - true if alarm is canceled else false 
.RE
.PP

.PP
Definition at line 147 of file car_panel\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for VROOM from the source code\&.
