.TH "4bit R2R with LEDs" 3 "Thu Dec 11 2014" "Version v0.01" "VROOM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
4bit R2R with LEDs \- 
.PP
This is a driver for the 4bit R2R DAC with 4 LEDs This is used to be able to use an oscilloscope to measure when different tasks are running\&.  

.SS "Modules"

.in +1c
.ti -1c
.RI "\fBPublic\fP"
.br
.ti -1c
.RI "\fBPrivate\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
This is a driver for the 4bit R2R DAC with 4 LEDs This is used to be able to use an oscilloscope to measure when different tasks are running\&. 


.SH "Author"
.PP 
Generated automatically by Doxygen for VROOM from the source code\&.
