.TH "LED define" 3 "Thu Dec 11 2014" "Version v0.01" "VROOM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
LED define \- 
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBR2R_LED_ON\fP   1"
.br
.ti -1c
.RI "#define \fBR2R_LED_OFF\fP   0"
.br
.in -1c
.SH "Detailed Description"
.PP 
LED on/off define 
.SH "Macro Definition Documentation"
.PP 
.SS "#define R2R_LED_OFF   0"

.PP
Definition at line 40 of file r2r_led\&.h\&.
.SS "#define R2R_LED_ON   1"

.PP
Definition at line 39 of file r2r_led\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for VROOM from the source code\&.
