.TH "Port" 3 "Thu Dec 11 2014" "Version v0.01" "VROOM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Port \- 
.PP
Port define for the r2r_led\&.  

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBR2R_PORT\fP   \fBCONFIG_PORT_R2R\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Port define for the r2r_led\&. 


.SH "Macro Definition Documentation"
.PP 
.SS "#define R2R_PORT   \fBCONFIG_PORT_R2R\fP"

.PP
Definition at line 30 of file r2r_led\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for VROOM from the source code\&.
