.TH "Data Communication" 3 "Wed Dec 3 2014" "Version v0.01" "VROOM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Data Communication \- 
.SS "Modules"

.in +1c
.ti -1c
.RI "\fBSPI Driver\fP"
.br
.RI "\fIThis is a driver for the SPI bus on the ATMEGA family processors\&. \fP"
.ti -1c
.RI "\fBUART Driver\fP"
.br
.RI "\fIThis is a driver for the UART0-1 on the ATMEGA family processors\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 

.SH "Author"
.PP 
Generated automatically by Doxygen for VROOM from the source code\&.
