.TH "FIXED_TIME" 3 "Sun Nov 30 2014" "Version v0.01" "VROOM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FIXED_TIME \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <time\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "uint16_t \fByear\fP"
.br
.ti -1c
.RI "uint8_t \fBmon\fP"
.br
.ti -1c
.RI "uint8_t \fBday\fP"
.br
.ti -1c
.RI "uint8_t \fBhour\fP"
.br
.ti -1c
.RI "uint8_t \fBmin\fP"
.br
.ti -1c
.RI "uint8_t \fBsec\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 14 of file time\&.h\&.
.SH "Field Documentation"
.PP 
.SS "uint8_t day"

.PP
Definition at line 18 of file time\&.h\&.
.SS "uint8_t hour"

.PP
Definition at line 19 of file time\&.h\&.
.SS "uint8_t min"

.PP
Definition at line 20 of file time\&.h\&.
.SS "uint8_t mon"

.PP
Definition at line 17 of file time\&.h\&.
.SS "uint8_t sec"

.PP
Definition at line 21 of file time\&.h\&.
.SS "uint16_t year"

.PP
Definition at line 16 of file time\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VROOM from the source code\&.
