.TH "D:/Dropbox/Skole Opgaver/ICT Engineering/7th Semester/Bachelor Project/Source Code/VROOM/VROOM_working/sensors/accelerometer/lis331hh.c" 3 "Wed Dec 3 2014" "Version v0.01" "VROOM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/Dropbox/Skole Opgaver/ICT Engineering/7th Semester/Bachelor Project/Source Code/VROOM/VROOM_working/sensors/accelerometer/lis331hh.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <avr/interrupt\&.h>\fP
.br
\fC#include 'lis331hh\&.h'\fP
.br
\fC#include '\&.\&./\&.\&./data_comm/spi/spi\&.h'\fP
.br
\fC#include '\&.\&./sensor_scheduler\&.h'\fP
.br
\fC#include <util/delay\&.h>\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBACC_SCALE_FACTOR\fP   0\&.00017"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBACC_STATE\fP { \fBINIT\fP, \fBRUNNING\fP }"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "static void \fB_acc_callback\fP (uint8_t *__data)"
.br
.ti -1c
.RI "static void \fB_acc_read_from_reg\fP (uint8_t __reg, uint8_t __no_of_dummy_bytes)"
.br
.ti -1c
.RI "void \fBacc_init\fP (uint8_t cs_pin, \fBACC_POWER_MODE\fP power_mode, \fBACC_OUTPUT_DATA_RATE\fP output_data_rate, \fBACC_FULL_SCALE\fP full_scale)"
.br
.RI "\fIInitializes the driver\&. \fP"
.ti -1c
.RI "void \fBacc_measure\fP (void)"
.br
.RI "\fIStarts one measure routine\&. \fP"
.ti -1c
.RI "float \fBacc_get_x_axis\fP (void)"
.br
.RI "\fIGets the latest measured x axis value\&. \fP"
.ti -1c
.RI "float \fBacc_get_y_axis\fP (void)"
.br
.RI "\fIGets the latest measured y axis value\&. \fP"
.ti -1c
.RI "float \fBacc_get_z_axis\fP (void)"
.br
.RI "\fIGets the latest measured z axis value\&. \fP"
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "static uint8_t \fB_scale_multiplier\fP = 1"
.br
.ti -1c
.RI "static int16_t \fB_x_axis\fP = 0"
.br
.ti -1c
.RI "static int16_t \fB_y_axis\fP = 0"
.br
.ti -1c
.RI "static int16_t \fB_z_axis\fP = 0"
.br
.ti -1c
.RI "static int8_t \fB_handle\fP = -1"
.br
.ti -1c
.RI "static uint8_t \fB_send_setup\fP [6]"
.br
.ti -1c
.RI "static uint8_t \fB_send_read\fP [7]"
.br
.ti -1c
.RI "static \fBACC_STATE\fP \fB_state\fP"
.br
.in -1c
.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBACC_STATE\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIINIT \fP\fP
.TP
\fB\fIRUNNING \fP\fP
.PP
Definition at line 25 of file lis331hh\&.c\&.
.SH "Variable Documentation"
.PP 
.SS "int8_t _handle = -1\fC [static]\fP"

.PP
Definition at line 37 of file lis331hh\&.c\&.
.SS "uint8_t _scale_multiplier = 1\fC [static]\fP"

.PP
Definition at line 31 of file lis331hh\&.c\&.
.SS "uint8_t _send_read[7]\fC [static]\fP"

.PP
Definition at line 39 of file lis331hh\&.c\&.
.SS "uint8_t _send_setup[6]\fC [static]\fP"

.PP
Definition at line 38 of file lis331hh\&.c\&.
.SS "\fBACC_STATE\fP _state\fC [static]\fP"

.PP
Definition at line 41 of file lis331hh\&.c\&.
.SS "int16_t _x_axis = 0\fC [static]\fP"

.PP
Definition at line 33 of file lis331hh\&.c\&.
.SS "int16_t _y_axis = 0\fC [static]\fP"

.PP
Definition at line 34 of file lis331hh\&.c\&.
.SS "int16_t _z_axis = 0\fC [static]\fP"

.PP
Definition at line 35 of file lis331hh\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for VROOM from the source code\&.
