.TH "D:/Dropbox/Skole Opgaver/ICT Engineering/7th Semester/Bachelor Project/Source Code/VROOM/VROOM_working/sensors/accelerometer/lis331hh.c" 3 "Tue Dec 2 2014" "Version v0.01" "VROOM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/Dropbox/Skole Opgaver/ICT Engineering/7th Semester/Bachelor Project/Source Code/VROOM/VROOM_working/sensors/accelerometer/lis331hh.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <avr/interrupt\&.h>\fP
.br
\fC#include 'lis331hh\&.h'\fP
.br
\fC#include '\&.\&./\&.\&./data_comm/spi/spi\&.h'\fP
.br
\fC#include '\&.\&./sensor_scheduler\&.h'\fP
.br
\fC#include <util/delay\&.h>\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBACC_SCALE_FACTOR\fP   0\&.00017"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBACC_STATE\fP { \fBINIT\fP, \fBRUNNING\fP }"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "static void \fB_acc_callback\fP (uint8_t *__data)"
.br
.ti -1c
.RI "static void \fB_acc_read_from_reg\fP (uint8_t __reg, uint8_t __no_of_dummy_bytes)"
.br
.ti -1c
.RI "void \fBacc_init\fP (uint8_t __cs_pin, ACC_POWER_MODE __power_mode, ACC_OUTPUT_DATA_RATE __output_data_rate, ACC_FULL_SCALE __full_scale)"
.br
.ti -1c
.RI "void \fBacc_measure\fP (void)"
.br
.ti -1c
.RI "float \fBacc_get_x_axis\fP (void)"
.br
.ti -1c
.RI "float \fBacc_get_y_axis\fP (void)"
.br
.ti -1c
.RI "float \fBacc_get_z_axis\fP (void)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "static int16_t \fB_x_axis\fP = 0"
.br
.ti -1c
.RI "static int16_t \fB_y_axis\fP = 0"
.br
.ti -1c
.RI "static int16_t \fB_z_axis\fP = 0"
.br
.ti -1c
.RI "static int8_t \fB_handle\fP = -1"
.br
.ti -1c
.RI "static uint8_t \fB_send_setup\fP [6]"
.br
.ti -1c
.RI "static uint8_t \fB_send_read\fP [7]"
.br
.ti -1c
.RI "static \fBACC_STATE\fP \fB_state\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
: 01-09-2014 09:22:18 : Andi Degn : 0\&.2 
.PP
Definition in file \fBlis331hh\&.c\fP\&.
.SH "Macro Definition Documentation"
.PP 
.SS "#define ACC_SCALE_FACTOR   0\&.00017"

.PP
\fBNote:\fP
.RS 4
Complies MISRO 2004 standards 
.RE
.PP

.PP
Definition at line 24 of file lis331hh\&.c\&.
.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBACC_STATE\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIINIT \fP\fP
.TP
\fB\fIRUNNING \fP\fP
.PP
Definition at line 30 of file lis331hh\&.c\&.
.SH "Variable Documentation"
.PP 
.SS "int8_t _handle = -1\fC [static]\fP"

.PP
Definition at line 40 of file lis331hh\&.c\&.
.SS "uint8_t _send_read[7]\fC [static]\fP"

.PP
Definition at line 42 of file lis331hh\&.c\&.
.SS "uint8_t _send_setup[6]\fC [static]\fP"

.PP
Definition at line 41 of file lis331hh\&.c\&.
.SS "\fBACC_STATE\fP _state\fC [static]\fP"

.PP
Definition at line 44 of file lis331hh\&.c\&.
.SS "int16_t _x_axis = 0\fC [static]\fP"

.PP
Definition at line 36 of file lis331hh\&.c\&.
.SS "int16_t _y_axis = 0\fC [static]\fP"

.PP
Definition at line 37 of file lis331hh\&.c\&.
.SS "int16_t _z_axis = 0\fC [static]\fP"

.PP
Definition at line 38 of file lis331hh\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for VROOM from the source code\&.
