.TH "D:/Dropbox/Skole Opgaver/ICT Engineering/7th Semester/Bachelor Project/Source Code/VROOM/VROOM_working/sensors/accelerometer/lis331hh.h" 3 "Wed Dec 3 2014" "Version v0.01" "VROOM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/Dropbox/Skole Opgaver/ICT Engineering/7th Semester/Bachelor Project/Source Code/VROOM/VROOM_working/sensors/accelerometer/lis331hh.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <avr/io\&.h>\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBACC_CTRL_REG1\fP   0x20"
.br
.ti -1c
.RI "#define \fBACC_Xen\fP   0"
.br
.ti -1c
.RI "#define \fBACC_Yen\fP   1"
.br
.ti -1c
.RI "#define \fBACC_Zen\fP   2"
.br
.ti -1c
.RI "#define \fBACC_DR0\fP   3"
.br
.ti -1c
.RI "#define \fBACC_DR1\fP   4"
.br
.ti -1c
.RI "#define \fBACC_PM0\fP   5"
.br
.ti -1c
.RI "#define \fBACC_PM1\fP   6"
.br
.ti -1c
.RI "#define \fBACC_PM2\fP   7"
.br
.ti -1c
.RI "#define \fBACC_CTRL_REG2\fP   0x21"
.br
.ti -1c
.RI "#define \fBACC_HPCF0\fP   0"
.br
.ti -1c
.RI "#define \fBACC_HPCF1\fP   1"
.br
.ti -1c
.RI "#define \fBACC_HPen1\fP   2"
.br
.ti -1c
.RI "#define \fBACC_HPen2\fP   3"
.br
.ti -1c
.RI "#define \fBACC_FDS\fP   4"
.br
.ti -1c
.RI "#define \fBACC_HPM0\fP   5"
.br
.ti -1c
.RI "#define \fBACC_HPM1\fP   6"
.br
.ti -1c
.RI "#define \fBACC_BOOT\fP   7"
.br
.ti -1c
.RI "#define \fBACC_CTRL_REG3\fP   0x22"
.br
.ti -1c
.RI "#define \fBACC_I1_CFG0\fP   0"
.br
.ti -1c
.RI "#define \fBACC_I1_CFG1\fP   1"
.br
.ti -1c
.RI "#define \fBACC_LIR1\fP   2"
.br
.ti -1c
.RI "#define \fBACC_I2_CFG0\fP   3"
.br
.ti -1c
.RI "#define \fBACC_I2_CFG1\fP   4"
.br
.ti -1c
.RI "#define \fBACC_LIR2\fP   5"
.br
.ti -1c
.RI "#define \fBACC_PP_OD\fP   6"
.br
.ti -1c
.RI "#define \fBACC_IHL\fP   7"
.br
.ti -1c
.RI "#define \fBACC_CTRL_REG4\fP   0x23"
.br
.ti -1c
.RI "#define \fBACC_SIM\fP   0"
.br
.ti -1c
.RI "#define \fBACC_ST\fP   1"
.br
.ti -1c
.RI "#define \fBACC_STsign\fP   3"
.br
.ti -1c
.RI "#define \fBACC_FS0\fP   4"
.br
.ti -1c
.RI "#define \fBACC_FS1\fP   5"
.br
.ti -1c
.RI "#define \fBACC_BLE\fP   6"
.br
.ti -1c
.RI "#define \fBACC_BDU\fP   7"
.br
.ti -1c
.RI "#define \fBACC_CTRL_REG5\fP   0x24"
.br
.ti -1c
.RI "#define \fBACC_TurnOn0\fP   0"
.br
.ti -1c
.RI "#define \fBACC_TurnOn1\fP   1"
.br
.ti -1c
.RI "#define \fBACC_READ_BIT\fP   7"
.br
.ti -1c
.RI "#define \fBACC_MULTI_BIT\fP   6"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBACC_POWER_MODE\fP { \fBACC_POWER_DOWN\fP = 0, \fBACC_NORMAL_MODE\fP = _BV(ACC_PM0), \fBACC_LOW_POWER_0_5\fP = _BV(ACC_PM1), \fBACC_LOW_POWER_1\fP = _BV(ACC_PM1) | _BV(ACC_PM0), \fBACC_LOW_POWER_2\fP = _BV(ACC_PM2), \fBACC_LOW_POWER_5\fP = _BV(ACC_PM2) | _BV(ACC_PM0), \fBACC_LOW_POWER_10\fP = _BV(ACC_PM2) | _BV(ACC_PM1) }"
.br
.RI "\fISpecifies the available power modes Output data rate frq  ACC_POWER_DOWN --- ACC_NORMAL_MODE ODR ACC_LOW_POWER_0_5 0\&.5 Hz ACC_LOW_POWER_1 1 Hz ACC_LOW_POWER_2 2 Hz ACC_LOW_POWER_5 5 Hz ACC_LOW_POWER_10 10 Hz \fP"
.ti -1c
.RI "enum \fBACC_OUTPUT_DATA_RATE\fP { \fBACC_ODR_50\fP = 0, \fBACC_ODR_100\fP = _BV(ACC_DR0), \fBACC_ODR_400\fP = _BV(ACC_DR1), \fBACC_ODR_1000\fP = _BV(ACC_DR1) | _BV(ACC_DR0) }"
.br
.RI "\fISpecifies the available Data Output Rates Output data rateLP Cut-off  ACC_ODR_50 50 Hz 37 Hz ACC_ODR_100 100 Hz 74 Hz ACC_ODR_400 400 Hz 292 Hz ACC_ODR_1000 1000 Hz 780 Hz \fP"
.ti -1c
.RI "enum \fBACC_High_Pass_CUT_OFF\fP { \fBACC_HPcoeff00\fP = 0, \fBACC_HPcoeff01\fP = _BV(ACC_HPCF0), \fBACC_HPcoeff10\fP = _BV(ACC_HPCF1), \fBACC_HPcoeff11\fP = _BV(ACC_HPCF1) | _BV(ACC_HPCF0) }"
.br
.RI "\fISpecifies the available High-pass filter cut-off frequency configuration 
.br
Look in datasheet page 24 for further information\&. \fP"
.ti -1c
.RI "enum \fBACC_FULL_SCALE\fP { \fBACC_6G\fP = 0, \fBACC_12G\fP = _BV(ACC_FS0), \fBACC_24G\fP = _BV(ACC_FS1) | _BV(ACC_FS0) }"
.br
.RI "\fISpecifies the available Full-scale selections 
.br
\&. \fP"
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBacc_init\fP (uint8_t cs_pin, \fBACC_POWER_MODE\fP power_mode, \fBACC_OUTPUT_DATA_RATE\fP output_data_rate, \fBACC_FULL_SCALE\fP full_scale)"
.br
.RI "\fIInitializes the driver\&. \fP"
.ti -1c
.RI "void \fBacc_measure\fP (void)"
.br
.RI "\fIStarts one measure routine\&. \fP"
.ti -1c
.RI "float \fBacc_get_x_axis\fP (void)"
.br
.RI "\fIGets the latest measured x axis value\&. \fP"
.ti -1c
.RI "float \fBacc_get_y_axis\fP (void)"
.br
.RI "\fIGets the latest measured y axis value\&. \fP"
.ti -1c
.RI "float \fBacc_get_z_axis\fP (void)"
.br
.RI "\fIGets the latest measured z axis value\&. \fP"
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for VROOM from the source code\&.
