.TH "Main file" 3 "Thu Dec 11 2014" "Version v0.01" "VROOM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Main file \- 
.PP
The main file where the system is initiated and started\&.  

.SS "Modules"

.in +1c
.ti -1c
.RI "\fBCurrent function\fP"
.br
.RI "\fIDefines what context of the program to be executed\&. \fP"
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBF_CPU\fP   11059200UL"
.br
.ti -1c
.RI "#define \fBON\fP   1"
.br
.ti -1c
.RI "#define \fBOFF\fP   0"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP (void)"
.br
.RI "\fIMain function\&. The system is started here\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
The main file where the system is initiated and started\&. 


.SH "Macro Definition Documentation"
.PP 
.SS "#define F_CPU   11059200UL"

.PP
Definition at line 25 of file run\&.c\&.
.SS "#define OFF   0"

.PP
Definition at line 27 of file run\&.c\&.
.SS "#define ON   1"

.PP
Definition at line 26 of file run\&.c\&.
.SH "Function Documentation"
.PP 
.SS "int main (void)"

.PP
Main function\&. The system is started here\&. 
.PP
Definition at line 49 of file run\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for VROOM from the source code\&.
