.TH "Current function" 3 "Thu Dec 11 2014" "Version v0.01" "VROOM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Current function \- 
.PP
Defines what context of the program to be executed\&.  

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBUNIT_TEST\fP   \fBOFF\fP"
.br
.ti -1c
.RI "#define \fBMODULE_TEST_SENSORS\fP   \fBOFF\fP"
.br
.ti -1c
.RI "#define \fBMODULE_TEST_SIM908\fP   \fBOFF\fP"
.br
.ti -1c
.RI "#define \fBMODULE_TEST_CAR_PANEL\fP   \fBOFF\fP"
.br
.ti -1c
.RI "#define \fBMODULE_TEST_UART\fP   \fBOFF\fP"
.br
.ti -1c
.RI "#define \fBINTEGRATION_TEST_SIM908_SENSORS\fP   \fBON\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Defines what context of the program to be executed\&. 


.PP
\fBNote:\fP
.RS 4
To run system in normal full functionality, INTEGRATION_TEST_SIM908_SENSORS must be 'ON' and all other must be 'OFF' 
.RE
.PP

.SH "Macro Definition Documentation"
.PP 
.SS "#define INTEGRATION_TEST_SIM908_SENSORS   \fBON\fP"

.PP
Definition at line 43 of file run\&.c\&.
.SS "#define MODULE_TEST_CAR_PANEL   \fBOFF\fP"

.PP
Definition at line 40 of file run\&.c\&.
.SS "#define MODULE_TEST_SENSORS   \fBOFF\fP"

.PP
Definition at line 38 of file run\&.c\&.
.SS "#define MODULE_TEST_SIM908   \fBOFF\fP"

.PP
Definition at line 39 of file run\&.c\&.
.SS "#define MODULE_TEST_UART   \fBOFF\fP"

.PP
Definition at line 41 of file run\&.c\&.
.SS "#define UNIT_TEST   \fBOFF\fP"

.PP
Definition at line 36 of file run\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for VROOM from the source code\&.
