.TH "D:/Dropbox/Skole Opgaver/ICT Engineering/7th Semester/Bachelor Project/Source Code/VROOM/VROOM_working/application/run.c" 3 "Thu Dec 11 2014" "Version v0.01" "VROOM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/Dropbox/Skole Opgaver/ICT Engineering/7th Semester/Bachelor Project/Source Code/VROOM/VROOM_working/application/run.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <avr/interrupt\&.h>\fP
.br
\fC#include <util/delay\&.h>\fP
.br
\fC#include <stdlib\&.h>\fP
.br
\fC#include 'scheduler/scheduler\&.h'\fP
.br
\fC#include '\&.\&./hardware_boards/sim908/sim908\&.h'\fP
.br
\fC#include '\&.\&./hardware_boards/car_panel/car_panel\&.h'\fP
.br
\fC#include '\&.\&./accident_logic/accident_data\&.h'\fP
.br
\fC#include '\&.\&./util/lcd_board/lcd/lcd\&.h'\fP
.br
\fC#include '\&.\&./util/r2r_led/r2r_led\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBF_CPU\fP   11059200UL"
.br
.ti -1c
.RI "#define \fBON\fP   1"
.br
.ti -1c
.RI "#define \fBOFF\fP   0"
.br
.ti -1c
.RI "#define \fBUNIT_TEST\fP   \fBOFF\fP"
.br
.ti -1c
.RI "#define \fBMODULE_TEST_SENSORS\fP   \fBOFF\fP"
.br
.ti -1c
.RI "#define \fBMODULE_TEST_SIM908\fP   \fBOFF\fP"
.br
.ti -1c
.RI "#define \fBMODULE_TEST_CAR_PANEL\fP   \fBOFF\fP"
.br
.ti -1c
.RI "#define \fBMODULE_TEST_UART\fP   \fBOFF\fP"
.br
.ti -1c
.RI "#define \fBINTEGRATION_TEST_SIM908_SENSORS\fP   \fBON\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP (void)"
.br
.RI "\fIMain function\&. The system is started here\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
05-09-2014 08:13:16 
.PP
\fBAuthor:\fP
.RS 4
Andi Degn 
.PP
Kenneth René Jensen 
.RE
.PP

.PP
Definition in file \fBrun\&.c\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for VROOM from the source code\&.
