.TH "Scheduler" 3 "Thu Dec 11 2014" "Version v0.01" "VROOM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Scheduler \- 
.PP
Basic task scheduler running cyclic execution of all the main tasks in the system\&.  

.SS "Modules"

.in +1c
.ti -1c
.RI "\fBPublic\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Basic task scheduler running cyclic execution of all the main tasks in the system\&. 


.PP
\fBNote:\fP
.RS 4
Complies MISRA 2004 standards 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for VROOM from the source code\&.
