.TH "Sensors" 3 "Thu Dec 11 2014" "Version v0.01" "VROOM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Sensors \- 
.SS "Modules"

.in +1c
.ti -1c
.RI "\fBLIS331HH\fP"
.br
.RI "\fIThis is a driver for the accelerometer LIS331HH on the ATMEGA family processors\&. \fP"
.ti -1c
.RI "\fBTC72_driver\fP"
.br
.RI "\fIThis is the driver for the temperature sensor tc72 on the ATMEGA family processors\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 

.SH "Author"
.PP 
Generated automatically by Doxygen for VROOM from the source code\&.
