.TH "D:/Dropbox/Skole Opgaver/ICT Engineering/7th Semester/Bachelor Project/Source Code/VROOM/VROOM_working/sensors/sensor_scheduler.h" 3 "Wed Dec 3 2014" "Version v0.01" "VROOM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/Dropbox/Skole Opgaver/ICT Engineering/7th Semester/Bachelor Project/Source Code/VROOM/VROOM_working/sensors/sensor_scheduler.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'thermometer/tc72\&.h'\fP
.br
\fC#include 'accelerometer/lis331hh\&.h'\fP
.br
\fC#include '\&.\&./util/timer/timer\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBscheduler_start\fP (void(*callback_function_ptr)(char __data))"
.br
.RI "\fIInitializes the scheduler\&. \fP"
.ti -1c
.RI "void \fBscheduler_acc_get_last_readings_sum\fP (int16_t *__buffer)"
.br
.RI "\fIFills up the supplied memory with vector lengths from the accelerometer\&. \fP"
.ti -1c
.RI "void \fBscheduler_acc_get_last_readings\fP (int16_t *__buffer)"
.br
.RI "\fIFills up the supplied memory with the last readings from the accelerometer (x, y, z) \fP"
.ti -1c
.RI "float \fBscheduler_temp_get_last_reading\fP (void)"
.br
.RI "\fIReturns the last temperature reading\&. \fP"
.ti -1c
.RI "void \fBscheduler_release\fP (void)"
.br
.RI "\fIReleases the scheduler\&. \fP"
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for VROOM from the source code\&.
