.TH "D:/Dropbox/Skole Opgaver/ICT Engineering/7th Semester/Bachelor Project/Source Code/VROOM/VROOM_working/sensors/sensor_scheduler.c" 3 "Wed Dec 3 2014" "Version v0.01" "VROOM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/Dropbox/Skole Opgaver/ICT Engineering/7th Semester/Bachelor Project/Source Code/VROOM/VROOM_working/sensors/sensor_scheduler.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <util/delay\&.h>\fP
.br
\fC#include <math\&.h>\fP
.br
\fC#include 'sensor_scheduler\&.h'\fP
.br
\fC#include '\&.\&./vroom_config\&.h'\fP
.br

.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBSENSOR_STATE\fP { \fBstate_tc72_init\fP, \fBstate_acc_init\fP, \fBstate_timer_init\fP, \fBstate_idle\fP, \fBstate_tc72_read\fP, \fBstate_acc_read\fP, \fBstate_store_in_buffers\fP }"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBscheduler_start\fP (void(*callback_function_ptr)(char __data))"
.br
.RI "\fIInitializes the scheduler\&. \fP"
.ti -1c
.RI "void \fBscheduler_acc_get_last_readings_sum\fP (int16_t *__buffer)"
.br
.RI "\fIFills up the supplied memory with vector lengths from the accelerometer\&. \fP"
.ti -1c
.RI "void \fBscheduler_acc_get_last_readings\fP (int16_t *__buffer)"
.br
.RI "\fIFills up the supplied memory with the last readings from the accelerometer (x, y, z) \fP"
.ti -1c
.RI "float \fBscheduler_temp_get_last_reading\fP (void)"
.br
.RI "\fIReturns the last temperature reading\&. \fP"
.ti -1c
.RI "void \fBscheduler_release\fP (void)"
.br
.RI "\fIReleases the scheduler\&. \fP"
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "static int16_t \fB_x_axis_buffer\fP [\fBCONFIG_ALARM_CRASH_NO_OF_READINGS\fP]"
.br
.ti -1c
.RI "static int16_t \fB_y_axis_buffer\fP [\fBCONFIG_ALARM_CRASH_NO_OF_READINGS\fP]"
.br
.ti -1c
.RI "static int16_t \fB_z_axis_buffer\fP [\fBCONFIG_ALARM_CRASH_NO_OF_READINGS\fP]"
.br
.ti -1c
.RI "static float \fB_temperature\fP = \fBCONFIG_ALARM_FIRE_TEMP_INIT\fP"
.br
.ti -1c
.RI "static \fBSENSOR_STATE\fP \fB_state\fP"
.br
.ti -1c
.RI "static void(* \fB_callback_function_ptr\fP )(char __data)"
.br
.ti -1c
.RI "static uint8_t \fB_acc_buffer_tail\fP = 0"
.br
.in -1c
.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBSENSOR_STATE\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIstate_tc72_init \fP\fP
.TP
\fB\fIstate_acc_init \fP\fP
.TP
\fB\fIstate_timer_init \fP\fP
.TP
\fB\fIstate_idle \fP\fP
.TP
\fB\fIstate_tc72_read \fP\fP
.TP
\fB\fIstate_acc_read \fP\fP
.TP
\fB\fIstate_store_in_buffers \fP\fP
.PP
Definition at line 9 of file sensor_scheduler\&.c\&.
.SH "Variable Documentation"
.PP 
.SS "uint8_t _acc_buffer_tail = 0\fC [static]\fP"

.PP
Definition at line 27 of file sensor_scheduler\&.c\&.
.SS "void(* _callback_function_ptr)(char __data)\fC [static]\fP"

.PP
Definition at line 25 of file sensor_scheduler\&.c\&.
.SS "\fBSENSOR_STATE\fP _state\fC [static]\fP"

.PP
Definition at line 24 of file sensor_scheduler\&.c\&.
.SS "float _temperature = \fBCONFIG_ALARM_FIRE_TEMP_INIT\fP\fC [static]\fP"

.PP
Definition at line 22 of file sensor_scheduler\&.c\&.
.SS "int16_t _x_axis_buffer[\fBCONFIG_ALARM_CRASH_NO_OF_READINGS\fP]\fC [static]\fP"

.PP
Definition at line 19 of file sensor_scheduler\&.c\&.
.SS "int16_t _y_axis_buffer[\fBCONFIG_ALARM_CRASH_NO_OF_READINGS\fP]\fC [static]\fP"

.PP
Definition at line 20 of file sensor_scheduler\&.c\&.
.SS "int16_t _z_axis_buffer[\fBCONFIG_ALARM_CRASH_NO_OF_READINGS\fP]\fC [static]\fP"

.PP
Definition at line 21 of file sensor_scheduler\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for VROOM from the source code\&.
