.TH "Flag codes" 3 "Wed Dec 3 2014" "Version v0.01" "VROOM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Flag codes \- 
.PP
Defines for the flag list responses\&.  

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBSIM908_FLAG_WAITING\fP   0"
.br
.ti -1c
.RI "#define \fBSIM908_FLAG_OK\fP   1"
.br
.ti -1c
.RI "#define \fBSIM908_FLAG_ERROR\fP   2"
.br
.ti -1c
.RI "#define \fBSIM908_FLAG_FTP_PUT_OPEN\fP   10"
.br
.ti -1c
.RI "#define \fBSIM908_FLAG_FTP_PUT_CLOSE\fP   11"
.br
.ti -1c
.RI "#define \fBSIM908_FLAG_FTP_PUT_SUCCESS\fP   12"
.br
.ti -1c
.RI "#define \fBSIM908_FLAG_FTP_PUT_ERROR\fP   13"
.br
.ti -1c
.RI "#define \fBSIM908_FLAG_FTP_SENDING\fP   14"
.br
.ti -1c
.RI "#define \fBSIM908_FLAG_GPS_OK\fP   20"
.br
.ti -1c
.RI "#define \fBSIM908_FLAG_GPS_PULL\fP   21"
.br
.ti -1c
.RI "#define \fBSIM908_FLAG_GPS_PULL_OK\fP   22"
.br
.ti -1c
.RI "#define \fBSIM908_FLAG_RUNNING\fP   100"
.br
.in -1c
.SH "Detailed Description"
.PP 
Defines for the flag list responses\&. 


.SH "Macro Definition Documentation"
.PP 
.SS "#define SIM908_FLAG_ERROR   2"

.PP
Definition at line 23 of file sim908\&.c\&.
.SS "#define SIM908_FLAG_FTP_PUT_CLOSE   11"

.PP
Definition at line 26 of file sim908\&.c\&.
.SS "#define SIM908_FLAG_FTP_PUT_ERROR   13"

.PP
Definition at line 28 of file sim908\&.c\&.
.SS "#define SIM908_FLAG_FTP_PUT_OPEN   10"

.PP
Definition at line 25 of file sim908\&.c\&.
.SS "#define SIM908_FLAG_FTP_PUT_SUCCESS   12"

.PP
Definition at line 27 of file sim908\&.c\&.
.SS "#define SIM908_FLAG_FTP_SENDING   14"

.PP
Definition at line 29 of file sim908\&.c\&.
.SS "#define SIM908_FLAG_GPS_OK   20"

.PP
Definition at line 31 of file sim908\&.c\&.
.SS "#define SIM908_FLAG_GPS_PULL   21"

.PP
Definition at line 32 of file sim908\&.c\&.
.SS "#define SIM908_FLAG_GPS_PULL_OK   22"

.PP
Definition at line 33 of file sim908\&.c\&.
.SS "#define SIM908_FLAG_OK   1"

.PP
Definition at line 22 of file sim908\&.c\&.
.SS "#define SIM908_FLAG_RUNNING   100"

.PP
Definition at line 35 of file sim908\&.c\&.
.SS "#define SIM908_FLAG_WAITING   0"

.PP
Definition at line 21 of file sim908\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for VROOM from the source code\&.
