.TH "D:/Dropbox/Skole Opgaver/ICT Engineering/7th Semester/Bachelor Project/Source Code/VROOM/VROOM_working/hardware_boards/sim908/sim908.h" 3 "Wed Dec 3 2014" "Version v0.01" "VROOM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/Dropbox/Skole Opgaver/ICT Engineering/7th Semester/Bachelor Project/Source Code/VROOM/VROOM_working/hardware_boards/sim908/sim908.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <avr/io\&.h>\fP
.br
\fC#include <stdbool\&.h>\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBSTK600\fP"
.br
.ti -1c
.RI "#define \fBDRIVER_PORT\fP   PORTE"
.br
.ti -1c
.RI "#define \fBGSM_PORT\fP   PORTE"
.br
.ti -1c
.RI "#define \fBGPS_PORT\fP   PORTE"
.br
.ti -1c
.RI "#define \fBGSM_ENABLE_PIN\fP   PE3"
.br
.ti -1c
.RI "#define \fBGPS_ENABLE_PIN\fP   PE4"
.br
.ti -1c
.RI "#define \fBCE_PIN\fP   PE5"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBSIM908_init\fP (void)"
.br
.RI "\fIInitiates the SIM908 module\&. \fP"
.ti -1c
.RI "void \fBSIM908_start\fP (void)"
.br
.RI "\fIStarts the SIM908 module\&. \fP"
.ti -1c
.RI "bool \fBSIM908_cmd\fP (const char *cmd, bool __wait_for_ok)"
.br
.RI "\fIUsed for sending AT SET commands\&. \fP"
.ti -1c
.RI "void \fBset_MSD_data\fP (uint32_t *__UTC_sec, int32_t *__latitude, int32_t *__longitude, uint8_t *__course)"
.br
.RI "\fISets the MSD with relevant information given from GPS response\&. \fP"
.ti -1c
.RI "void \fBcall_PSAP\fP (void)"
.br
.RI "\fICalling Public-safety answering point\&. \fP"
.ti -1c
.RI "void \fBsend_MSD\fP (const char *__vroom_id)"
.br
.RI "\fISends MSD binary file to FTP server\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
25-09-2014 13:09:36 
.PP
\fBAuthor:\fP
.RS 4
Andi Degn 
.PP
Kenneth René Jensen 
.RE
.PP
\fBVersion:\fP
.RS 4
0\&.5 
.RE
.PP

.PP
Definition in file \fBsim908\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for VROOM from the source code\&.
