.TH "D:/Dropbox/Skole Opgaver/ICT Engineering/7th Semester/Bachelor Project/Source Code/VROOM/VROOM_working/hardware_boards/sim908/sim908.c" 3 "Sun Nov 30 2014" "Version v0.01" "VROOM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/Dropbox/Skole Opgaver/ICT Engineering/7th Semester/Bachelor Project/Source Code/VROOM/VROOM_working/hardware_boards/sim908/sim908.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <stdlib\&.h>\fP
.br
\fC#include <string\&.h>\fP
.br
\fC#include <util/delay\&.h>\fP
.br
\fC#include 'sim908\&.h'\fP
.br
\fC#include 'at_commands\&.h'\fP
.br
\fC#include '\&.\&./\&.\&./data_comm/uart/uart\&.h'\fP
.br
\fC#include '\&.\&./\&.\&./accident_logic/accident_data\&.h'\fP
.br
\fC#include '\&.\&./\&.\&./util/time\&.h'\fP
.br
\fC#include '\&.\&./\&.\&./vroom_config\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBRX_BUFFER_SIZE\fP   128"
.br
.ti -1c
.RI "#define \fBDDR\fP(x)   (*(&x - 1))"
.br
.ti -1c
.RI "#define \fBPIN\fP(x)   (*(&x - 2))"
.br
.ti -1c
.RI "#define \fBRETRY_ATTEMPTS\fP   10"
.br
.ti -1c
.RI "#define \fBCONNECTION_RETRY_DELAY_IN_MS\fP   50"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fB_SIM908_callback\fP (char data)"
.br
.ti -1c
.RI "void \fB_PC_callback\fP (char data)"
.br
.ti -1c
.RI "void \fBSIM908_init\fP (void)"
.br
.RI "\fIInitiates the SIM908 module\&. \fP"
.ti -1c
.RI "void \fBSIM908_start\fP (void)"
.br
.RI "\fIStarts the SIM908 module in following procedure\&. setup global settings -> setup GSM -> setup GPS -> enable GSM communication -> setup FTP\&. \fP"
.ti -1c
.RI "bool \fBSIM908_cmd\fP (const char *__cmd, bool __wait_for_ok)"
.br
.RI "\fIUsed for sending AT SET commands\&. \fP"
.ti -1c
.RI "void \fBset_MSD_data\fP (uint32_t *__UTC_sec, int32_t *__latitude, int32_t *__longitude, uint8_t *__course)"
.br
.RI "\fISets the MSD with relevant information given from GPS response\&. \fP"
.ti -1c
.RI "void \fBcall_PSAP\fP (void)"
.br
.RI "\fICalling Public-safety answering point\&. \fP"
.ti -1c
.RI "void \fBsend_MSD\fP (const char *__vroom_id)"
.br
.RI "\fISends MSD binary file to FTP server 1: Create filename: AT+FTPPUTNAME='<filename>' 2: Open bearer AT+SAPBR=1,1 3: Open FTP PUT session AT+FTPPUT=1 4: Set write data AT+FTPPUT=2,140 5: Write text (140 bytes) 6: End write session AT+FTPPUT=2,0 7: Close bearer AT+SAPBR=0,1\&. \fP"
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "char \fBEXT_MSD_FILENAME\fP [24]"
.br
.RI "\fIConstant vehicle class type definition\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 

.PP
\fBAuthor:\fP
.RS 4
: Kenneth René Jensen : 0\&.5 
.PP
.nf
This is the driver for GSM/GPRS/GPS module sim908
.fi
.PP
.RE
.PP

.PP
Definition in file \fBsim908\&.c\fP\&.
.SH "Macro Definition Documentation"
.PP 
.SS "#define CONNECTION_RETRY_DELAY_IN_MS   50"

.PP
Definition at line 66 of file sim908\&.c\&.
.SS "#define DDR(x)   (*(&x - 1))"

.PP
Definition at line 62 of file sim908\&.c\&.
.SS "#define PIN(x)   (*(&x - 2))"

.PP
Definition at line 63 of file sim908\&.c\&.
.SS "#define RETRY_ATTEMPTS   10"

.PP
Definition at line 65 of file sim908\&.c\&.
.SS "#define RX_BUFFER_SIZE   128"

.PP
\fBNote:\fP
.RS 4
NOT YET Complies MISRO 2004 standards 
.RE
.PP

.PP
Definition at line 20 of file sim908\&.c\&.
.SH "Function Documentation"
.PP 
.SS "void _PC_callback (chardata)"

.PP
Definition at line 624 of file sim908\&.c\&.
.SS "void _SIM908_callback (chardata)"

.PP
Definition at line 565 of file sim908\&.c\&.
.SH "Variable Documentation"
.PP 
.SS "char EXT_MSD_FILENAME[24]"

.PP
Constant vehicle class type definition\&. 
.PP
\fBNote:\fP
.RS 4
Upper nibble contains class definition: [SA, L, M, N, O, T, G] @ Lower nibble contains class category definition: [1 - 7] @ Details: http://eur-lex.europa.eu/legal-content/EN/TXT/PDF/?uri=CELEX:32007L0046&from=EN 
.PP
.nf
                                                                          /
#define AD_VEHICLE_CLASS_L(category)    (1<<4 | category)   /* Motor vehicles with less than four wheels */
#define AD_VEHICLE_CLASS_M(category)    (2<<4 | category)   /* Power-driven vehicles having at least four wheels and used for the carriage of passengers */
#define AD_VEHICLE_CLASS_N(category)    (3<<4 | category)   /* Power-driven vehicles having at least four wheels and used for the carriage of goods */
#define AD_VEHICLE_CLASS_O(category)    (4<<4 | category)   /* Trailers (including semi–trailers) */
#define AD_VEHICLE_CLASS_T(category)    (5<<4 | category)   /* Agricultural and Forestry tractors */
#define AD_VEHICLE_CLASS_G(category)    (6<<4 | category)   /* Off-road vehicles */
#define AD_VEHICLE_CLASS_SA(category)   (7<<4 | category)   /* Special purpose vehicles (e\&.g\&. Ambulance, Hearse, Armoured vehicle or Motor caravan) */

.fi
.PP
.RE
.PP
Flag to detect if an alarm has been triggered 
.PP
.nf
                                                                          /
typedef enum {  EMERGENCY_NO_ALARM = 0,
                EMERGENCY_MANUAL_ALARM = 1,
                EMERGENCY_AUTO_ALARM = 2,
                EMERGENCY_ALARM_SENT = 3
} AD_EMERGENCY_FLAG;

.fi
.PP
.PP
Flag to detect the connection status 
.PP
\fBNote:\fP
.RS 4
Corresponding to CREG response in SIM908 p\&. 77 in AT Commands manual v\&. 1\&.02 
.PP
.nf
                                                                          /
typedef enum {  CREG_NOT_REGISTERED = 0,
                CREG_REGISTERED = 1,
                CREG_SEARCHING = 2,
                CREG_REGISTRATION_DENIED = 3,
                CREG_UNKNOWN = 4,
                CREG_REGISTERED_ROOMING = 5,
} AD_CONNECTION_STATUS_FLAG;

.fi
.PP
 
.RE
.PP

.PP
Definition at line 42 of file sim908\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for VROOM from the source code\&.
