.TH "Port" 3 "Thu Dec 11 2014" "Version v0.01" "VROOM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Port \- 
.PP
Defines the port(s) and pins for the communition to the SIM908 module\&.  

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBDRIVER_PORT\fP   \fBCONFIG_PORT_DRIVER_PORT\fP"
.br
.ti -1c
.RI "#define \fBGSM_PORT\fP   \fBCONFIG_PORT_GSM_PORT\fP"
.br
.ti -1c
.RI "#define \fBGPS_PORT\fP   \fBCONFIG_PORT_GPS_PORT\fP"
.br
.ti -1c
.RI "#define \fBGSM_ENABLE_PIN\fP   \fBCONFIG_PORT_GSM_ENABLE_PIN\fP"
.br
.ti -1c
.RI "#define \fBGPS_ENABLE_PIN\fP   \fBCONFIG_PORT_GPS_ENABLE_PIN\fP"
.br
.ti -1c
.RI "#define \fBCE_PIN\fP   \fBCONFIG_PORT_CE_PIN\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Defines the port(s) and pins for the communition to the SIM908 module\&. 


.SH "Macro Definition Documentation"
.PP 
.SS "#define CE_PIN   \fBCONFIG_PORT_CE_PIN\fP"

.PP
Definition at line 35 of file sim908\&.h\&.
.SS "#define DRIVER_PORT   \fBCONFIG_PORT_DRIVER_PORT\fP"

.PP
Definition at line 30 of file sim908\&.h\&.
.SS "#define GPS_ENABLE_PIN   \fBCONFIG_PORT_GPS_ENABLE_PIN\fP"

.PP
Definition at line 34 of file sim908\&.h\&.
.SS "#define GPS_PORT   \fBCONFIG_PORT_GPS_PORT\fP"

.PP
Definition at line 32 of file sim908\&.h\&.
.SS "#define GSM_ENABLE_PIN   \fBCONFIG_PORT_GSM_ENABLE_PIN\fP"

.PP
Definition at line 33 of file sim908\&.h\&.
.SS "#define GSM_PORT   \fBCONFIG_PORT_GSM_PORT\fP"

.PP
Definition at line 31 of file sim908\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for VROOM from the source code\&.
