.TH "Response literals" 3 "Wed Dec 3 2014" "Version v0.01" "VROOM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Response literals \- 
.PP
defines the AT response string literals  

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBSIM908_RESPONSE_RDY\fP   'RDY'"
.br
.ti -1c
.RI "#define \fBSIM908_RESPONSE_SKIP\fP   'AT+'"
.br
.ti -1c
.RI "#define \fBSIM908_RESPONSE_OK\fP   'OK'"
.br
.ti -1c
.RI "#define \fBSIM908_RESPONSE_ERROR\fP   'ERR'"
.br
.ti -1c
.RI "#define \fBSIM908_RESPONSE_CR_LF\fP   '\\r\\n'"
.br
.ti -1c
.RI "#define \fBSIM908_RESPONSE_LF_CR\fP   '\\n\\r'"
.br
.ti -1c
.RI "#define \fBSIM908_RESPONSE_AT\fP   'AT'"
.br
.ti -1c
.RI "#define \fBSIM908_RESPONSE_GPS_READY\fP   'GPS'"
.br
.ti -1c
.RI "#define \fBSIM908_RESPONSE_GPS_PULL\fP   '0,'"
.br
.ti -1c
.RI "#define \fBSIM908_RESPONSE_FTP_PUT\fP   '+F'"
.br
.ti -1c
.RI "#define \fBSIM908_RESPONSE_CREG\fP   '+CREG: '		/* +CREG: 1 = connected */"
.br
.in -1c
.SH "Detailed Description"
.PP 
defines the AT response string literals 


.SH "Macro Definition Documentation"
.PP 
.SS "#define SIM908_RESPONSE_AT   'AT'"

.PP
Definition at line 51 of file sim908\&.c\&.
.SS "#define SIM908_RESPONSE_CR_LF   '\\r\\n'"

.PP
Definition at line 49 of file sim908\&.c\&.
.SS "#define SIM908_RESPONSE_CREG   '+CREG: '		/* +CREG: 1 = connected */"

.PP
Definition at line 55 of file sim908\&.c\&.
.SS "#define SIM908_RESPONSE_ERROR   'ERR'"

.PP
Definition at line 48 of file sim908\&.c\&.
.SS "#define SIM908_RESPONSE_FTP_PUT   '+F'"

.PP
Definition at line 54 of file sim908\&.c\&.
.SS "#define SIM908_RESPONSE_GPS_PULL   '0,'"

.PP
Definition at line 53 of file sim908\&.c\&.
.SS "#define SIM908_RESPONSE_GPS_READY   'GPS'"

.PP
Definition at line 52 of file sim908\&.c\&.
.SS "#define SIM908_RESPONSE_LF_CR   '\\n\\r'"

.PP
Definition at line 50 of file sim908\&.c\&.
.SS "#define SIM908_RESPONSE_OK   'OK'"

.PP
Definition at line 47 of file sim908\&.c\&.
.SS "#define SIM908_RESPONSE_RDY   'RDY'"

.PP
Definition at line 44 of file sim908\&.c\&.
.SS "#define SIM908_RESPONSE_SKIP   'AT+'"

.PP
Definition at line 46 of file sim908\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for VROOM from the source code\&.
