.TH "Port" 3 "Wed Dec 3 2014" "Version v0.01" "VROOM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Port \- 
.PP
Defines the port(s) and pins for the communition to the SIM908 module\&.  

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBSTK600\fP"
.br
.ti -1c
.RI "#define \fBDRIVER_PORT\fP   PORTE"
.br
.ti -1c
.RI "#define \fBGSM_PORT\fP   PORTE"
.br
.ti -1c
.RI "#define \fBGPS_PORT\fP   PORTE"
.br
.ti -1c
.RI "#define \fBGSM_ENABLE_PIN\fP   PE3"
.br
.ti -1c
.RI "#define \fBGPS_ENABLE_PIN\fP   PE4"
.br
.ti -1c
.RI "#define \fBCE_PIN\fP   PE5"
.br
.in -1c
.SH "Detailed Description"
.PP 
Defines the port(s) and pins for the communition to the SIM908 module\&. 


.SH "Macro Definition Documentation"
.PP 
.SS "#define CE_PIN   PE5"

.PP
Definition at line 39 of file sim908\&.h\&.
.SS "#define DRIVER_PORT   PORTE"

.PP
Definition at line 34 of file sim908\&.h\&.
.SS "#define GPS_ENABLE_PIN   PE4"

.PP
Definition at line 38 of file sim908\&.h\&.
.SS "#define GPS_PORT   PORTE"

.PP
Definition at line 36 of file sim908\&.h\&.
.SS "#define GSM_ENABLE_PIN   PE3"

.PP
Definition at line 37 of file sim908\&.h\&.
.SS "#define GSM_PORT   PORTE"

.PP
Definition at line 35 of file sim908\&.h\&.
.SS "#define STK600"

.PP
Definition at line 31 of file sim908\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for VROOM from the source code\&.
