.TH "Flag codes" 3 "Thu Dec 11 2014" "Version v0.01" "VROOM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Flag codes \- 
.PP
Defines for the flag list responses\&.  

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBSIM908_FLAG_WAITING\fP   0U"
.br
.ti -1c
.RI "#define \fBSIM908_FLAG_OK\fP   1U"
.br
.ti -1c
.RI "#define \fBSIM908_FLAG_ERROR\fP   2U"
.br
.ti -1c
.RI "#define \fBSIM908_FLAG_FTP_PUT_OPEN\fP   10U"
.br
.ti -1c
.RI "#define \fBSIM908_FLAG_FTP_PUT_CLOSE\fP   11U"
.br
.ti -1c
.RI "#define \fBSIM908_FLAG_FTP_PUT_SUCCESS\fP   12U"
.br
.ti -1c
.RI "#define \fBSIM908_FLAG_FTP_PUT_ERROR\fP   13U"
.br
.ti -1c
.RI "#define \fBSIM908_FLAG_FTP_SENDING\fP   14U"
.br
.ti -1c
.RI "#define \fBSIM908_FLAG_GPS_OK\fP   20U"
.br
.ti -1c
.RI "#define \fBSIM908_FLAG_GPS_PULL\fP   21U"
.br
.ti -1c
.RI "#define \fBSIM908_FLAG_GPS_PULL_OK\fP   22U"
.br
.ti -1c
.RI "#define \fBSIM908_FLAG_RUNNING\fP   100U"
.br
.in -1c
.SH "Detailed Description"
.PP 
Defines for the flag list responses\&. 


.SH "Macro Definition Documentation"
.PP 
.SS "#define SIM908_FLAG_ERROR   2U"

.PP
Definition at line 24 of file sim908\&.c\&.
.SS "#define SIM908_FLAG_FTP_PUT_CLOSE   11U"

.PP
Definition at line 27 of file sim908\&.c\&.
.SS "#define SIM908_FLAG_FTP_PUT_ERROR   13U"

.PP
Definition at line 29 of file sim908\&.c\&.
.SS "#define SIM908_FLAG_FTP_PUT_OPEN   10U"

.PP
Definition at line 26 of file sim908\&.c\&.
.SS "#define SIM908_FLAG_FTP_PUT_SUCCESS   12U"

.PP
Definition at line 28 of file sim908\&.c\&.
.SS "#define SIM908_FLAG_FTP_SENDING   14U"

.PP
Definition at line 30 of file sim908\&.c\&.
.SS "#define SIM908_FLAG_GPS_OK   20U"

.PP
Definition at line 32 of file sim908\&.c\&.
.SS "#define SIM908_FLAG_GPS_PULL   21U"

.PP
Definition at line 33 of file sim908\&.c\&.
.SS "#define SIM908_FLAG_GPS_PULL_OK   22U"

.PP
Definition at line 34 of file sim908\&.c\&.
.SS "#define SIM908_FLAG_OK   1U"

.PP
Definition at line 23 of file sim908\&.c\&.
.SS "#define SIM908_FLAG_RUNNING   100U"

.PP
Definition at line 36 of file sim908\&.c\&.
.SS "#define SIM908_FLAG_WAITING   0U"

.PP
Definition at line 22 of file sim908\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for VROOM from the source code\&.
