.TH "SPI Driver" 3 "Tue Dec 2 2014" "Version v0.01" "VROOM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SPI Driver \- 
.SS "Modules"

.in +1c
.ti -1c
.RI "\fBPublic\fP"
.br
.ti -1c
.RI "\fBPrivate\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
This is a driver for the SPI bus on the ATMEGA family processors\&. 
.PP
\fBNote:\fP
.RS 4
Complies MISRO 2004 standards 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for VROOM from the source code\&.
