.TH "SPI Ports" 3 "Wed Dec 3 2014" "Version v0.01" "VROOM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SPI Ports \- 
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBDDR_SPI\fP   DDRB"
.br
.ti -1c
.RI "#define \fBSS\fP   PB0"
.br
.ti -1c
.RI "#define \fBSCK\fP   PB1"
.br
.ti -1c
.RI "#define \fBMOSI\fP   PB2"
.br
.ti -1c
.RI "#define \fBMISO\fP   PB3"
.br
.in -1c
.SH "Detailed Description"
.PP 
Defines for the ports and pins used by the SPI 
.SH "Macro Definition Documentation"
.PP 
.SS "#define DDR_SPI   DDRB"

.PP
Definition at line 14 of file spi\&.c\&.
.SS "#define MISO   PB3"

.PP
Definition at line 18 of file spi\&.c\&.
.SS "#define MOSI   PB2"

.PP
Definition at line 17 of file spi\&.c\&.
.SS "#define SCK   PB1"

.PP
Definition at line 16 of file spi\&.c\&.
.SS "#define SS   PB0"

.PP
Definition at line 15 of file spi\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for VROOM from the source code\&.
