.TH "SPI Ports" 3 "Thu Dec 11 2014" "Version v0.01" "VROOM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SPI Ports \- 
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBDDR_SPI\fP   \fBCONFIG_PORT_DDR_SPI\fP"
.br
.ti -1c
.RI "#define \fBSS\fP   \fBCONFIG_PORT_SS\fP"
.br
.ti -1c
.RI "#define \fBSCK\fP   \fBCONFIG_PORT_SCK\fP"
.br
.ti -1c
.RI "#define \fBMOSI\fP   \fBCONFIG_PORT_MOSI\fP"
.br
.ti -1c
.RI "#define \fBMISO\fP   \fBCONFIG_PORT_MISO\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Defines for the ports and pins used by the SPI 
.SH "Macro Definition Documentation"
.PP 
.SS "#define DDR_SPI   \fBCONFIG_PORT_DDR_SPI\fP"

.PP
Definition at line 15 of file spi\&.c\&.
.SS "#define MISO   \fBCONFIG_PORT_MISO\fP"

.PP
Definition at line 19 of file spi\&.c\&.
.SS "#define MOSI   \fBCONFIG_PORT_MOSI\fP"

.PP
Definition at line 18 of file spi\&.c\&.
.SS "#define SCK   \fBCONFIG_PORT_SCK\fP"

.PP
Definition at line 17 of file spi\&.c\&.
.SS "#define SS   \fBCONFIG_PORT_SS\fP"

.PP
Definition at line 16 of file spi\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for VROOM from the source code\&.
