.TH "SPI Active Level" 3 "Tue Dec 2 2014" "Version v0.01" "VROOM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SPI Active Level \- 
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBCS_INACTIVE\fP   0U"
.br
.ti -1c
.RI "#define \fBCS_ACTIVE\fP   1U"
.br
.in -1c
.SH "Detailed Description"
.PP 
defines inactive/active level for CS/CE 
.SH "Macro Definition Documentation"
.PP 
.SS "#define CS_ACTIVE   1U"

.PP
Definition at line 37 of file spi\&.c\&.
.SS "#define CS_INACTIVE   0U"

.PP
Definition at line 36 of file spi\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for VROOM from the source code\&.
