.TH "Sensor Scheduler" 3 "Wed Dec 3 2014" "Version v0.01" "VROOM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Sensor Scheduler \- 
.PP
Scheduler for reading temperature and accelerometer data in a sequential manner using a state machine\&.  

.SS "Modules"

.in +1c
.ti -1c
.RI "\fBPublic\fP"
.br
.ti -1c
.RI "\fBPrivate\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Scheduler for reading temperature and accelerometer data in a sequential manner using a state machine\&. 


.PP
\fBNote:\fP
.RS 4
NOT YET Complies MISRO 2004 standards 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for VROOM from the source code\&.
