.TH "Register addresses" 3 "Wed Dec 3 2014" "Version v0.01" "VROOM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Register addresses \- 
.PP
define for the addresses for the read and write command  

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBSDI_Read\fP   0x02U"
.br
.ti -1c
.RI "#define \fBSDI_Write\fP   0x80U"
.br
.in -1c
.SH "Detailed Description"
.PP 
define for the addresses for the read and write command 


.SH "Macro Definition Documentation"
.PP 
.SS "#define SDI_Read   0x02U"

.PP
Definition at line 15 of file tc72\&.c\&.
.SS "#define SDI_Write   0x80U"

.PP
Definition at line 16 of file tc72\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for VROOM from the source code\&.
