.TH "Public" 3 "Wed Dec 3 2014" "Version v0.01" "VROOM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Public \- 
.SS "Functions"

.in +1c
.ti -1c
.RI "bool \fBtest_module_uart_run\fP (const char *__uart_test_string, const char *__uart_compare_string)"
.br
.RI "\fIStarts the testing routine for uart0 and uart1\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 

.SH "Function Documentation"
.PP 
.SS "bool test_module_uart_run (const char *__uart_test_string, const char *__uart_compare_string)"

.PP
Starts the testing routine for uart0 and uart1\&. 
.PP
\fBParameters:\fP
.RS 4
\fIconst\fP char *__uart_test_string - string to be send 
.br
\fIconst\fP char *__uart_compare_string - string to be compared to
.RE
.PP
\fBReturns:\fP
.RS 4
bool - true = passed; false = failed 
.RE
.PP
\fBNote:\fP
.RS 4
To run this test uart0 and uart1 must be connect crossed\&. TX0->RX1, TX1->RX0 
.RE
.PP

.PP
Definition at line 25 of file test_module_uart\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for VROOM from the source code\&.
