.TH "D:/Dropbox/Skole Opgaver/ICT Engineering/7th Semester/Bachelor Project/Source Code/VROOM/VROOM_working/Tests/module/uart/test_module_uart.h" 3 "Sun Nov 30 2014" "Version v0.01" "VROOM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/Dropbox/Skole Opgaver/ICT Engineering/7th Semester/Bachelor Project/Source Code/VROOM/VROOM_working/Tests/module/uart/test_module_uart.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <stdbool\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "bool \fBtest_module_uart_run\fP (const char *__uart_test_string, const char *__uart_compare_string)"
.br
.RI "\fIStarts the testing routine for uart0 and uart1\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
: 26-09-2014 15:47:38 : Andi Degn 
.PP
Definition in file \fBtest_module_uart\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for VROOM from the source code\&.
