.TH "D:/Dropbox/Skole Opgaver/ICT Engineering/7th Semester/Bachelor Project/Source Code/VROOM/VROOM_working/Tests/module/uart/test_module_uart.c" 3 "Wed Dec 3 2014" "Version v0.01" "VROOM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/Dropbox/Skole Opgaver/ICT Engineering/7th Semester/Bachelor Project/Source Code/VROOM/VROOM_working/Tests/module/uart/test_module_uart.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <avr/io\&.h>\fP
.br
\fC#include <stdlib\&.h>\fP
.br
\fC#include <util/delay\&.h>\fP
.br
\fC#include 'test_module_uart\&.h'\fP
.br
\fC#include '\&.\&./\&.\&./\&.\&./data_comm/uart/uart\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBRECEIVED_DATA_LENGTH\fP   255"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "static bool \fB_validate_data\fP (void)"
.br
.ti -1c
.RI "static void \fB_data0_received\fP (char data)"
.br
.ti -1c
.RI "static void \fB_data1_received\fP (char data)"
.br
.ti -1c
.RI "bool \fBtest_module_uart_run\fP (const char *__uart_test_string, const char *__uart_compare_string)"
.br
.RI "\fIStarts the testing routine for uart0 and uart1\&. \fP"
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "static char * \fB_uart_compare_string\fP"
.br
.ti -1c
.RI "static char * \fB_uart_received_data\fP"
.br
.ti -1c
.RI "static char \fB_index\fP"
.br
.ti -1c
.RI "static uint16_t \fB_timeout_ctr\fP"
.br
.ti -1c
.RI "static bool \fB_roundtrip_complete\fP = false"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define RECEIVED_DATA_LENGTH   255"
\fBtest_module_uart\&.c\fP
.PP
Created: 26-09-2014 15:48:21 Author: Andi Degn 
.PP
Definition at line 13 of file test_module_uart\&.c\&.
.SH "Function Documentation"
.PP 
.SS "static void _data0_received (chardata)\fC [static]\fP"

.PP
Definition at line 99 of file test_module_uart\&.c\&.
.SS "static void _data1_received (chardata)\fC [static]\fP"

.PP
Definition at line 107 of file test_module_uart\&.c\&.
.SS "static bool _validate_data (void)\fC [static]\fP"

.PP
Definition at line 83 of file test_module_uart\&.c\&.
.SH "Variable Documentation"
.PP 
.SS "char _index\fC [static]\fP"

.PP
Definition at line 17 of file test_module_uart\&.c\&.
.SS "bool _roundtrip_complete = false\fC [static]\fP"

.PP
Definition at line 19 of file test_module_uart\&.c\&.
.SS "uint16_t _timeout_ctr\fC [static]\fP"

.PP
Definition at line 18 of file test_module_uart\&.c\&.
.SS "char* _uart_compare_string\fC [static]\fP"

.PP
Definition at line 15 of file test_module_uart\&.c\&.
.SS "char* _uart_received_data\fC [static]\fP"

.PP
Definition at line 16 of file test_module_uart\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for VROOM from the source code\&.
