.TH "D:/Dropbox/Skole Opgaver/ICT Engineering/7th Semester/Bachelor Project/Source Code/VROOM/VROOM_working/Tests/module/sensors/test_module_sensors.c" 3 "Wed Dec 3 2014" "Version v0.01" "VROOM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/Dropbox/Skole Opgaver/ICT Engineering/7th Semester/Bachelor Project/Source Code/VROOM/VROOM_working/Tests/module/sensors/test_module_sensors.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <stdlib\&.h>\fP
.br
\fC#include 'test_module_sensors\&.h'\fP
.br
\fC#include '\&.\&./\&.\&./\&.\&./hardware_boards/lcd_board/lcd/lcd\&.h'\fP
.br
\fC#include '\&.\&./\&.\&./\&.\&./sensors/sensor_scheduler\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBsensors_init\fP ()"
.br
.ti -1c
.RI "void \fBsensors_read_data\fP (void)"
.br
.ti -1c
.RI "void \fBsensors_print_data\fP (void)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "const char \fBdegree\fP = 0b011011111"
.br
.ti -1c
.RI "static int \fBx_axis\fP"
.br
.ti -1c
.RI "static int \fBy_axis\fP"
.br
.ti -1c
.RI "static int \fBz_axis\fP"
.br
.ti -1c
.RI "static float \fBtemp\fP"
.br
.ti -1c
.RI "static char \fBbuf\fP [10]"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
\fBAuthor:\fP
.RS 4
: Kenneth René Jensen : 0\&.1 
.RE
.PP

.PP
Definition in file \fBtest_module_sensors\&.c\fP\&.
.SH "Function Documentation"
.PP 
.SS "void sensors_init (void)"

.PP
\fBNote:\fP
.RS 4
NOT YET Complies MISRO 2004 standards 
.RE
.PP

.PP
Definition at line 22 of file test_module_sensors\&.c\&.
.SS "void sensors_print_data (void)"

.PP
Definition at line 39 of file test_module_sensors\&.c\&.
.SS "void sensors_read_data (void)"

.PP
Definition at line 31 of file test_module_sensors\&.c\&.
.SH "Variable Documentation"
.PP 
.SS "char buf[10]\fC [static]\fP"

.PP
Definition at line 20 of file test_module_sensors\&.c\&.
.SS "const char degree = 0b011011111"

.PP
\fBNote:\fP
.RS 4
NOT YET Complies MISRO 2004 standards 
.RE
.PP

.PP
Definition at line 17 of file test_module_sensors\&.c\&.
.SS "float temp\fC [static]\fP"

.PP
Definition at line 19 of file test_module_sensors\&.c\&.
.SS "int x_axis\fC [static]\fP"

.PP
Definition at line 18 of file test_module_sensors\&.c\&.
.SS "int y_axis\fC [static]\fP"

.PP
Definition at line 18 of file test_module_sensors\&.c\&.
.SS "int z_axis\fC [static]\fP"

.PP
Definition at line 18 of file test_module_sensors\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for VROOM from the source code\&.
