.TH "Module Test - Sensors" 3 "Thu Dec 11 2014" "Version v0.01" "VROOM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Module Test - Sensors \- 
.PP
This is a test for for the sensor module consisting of TC72 temperature sensor and accelerometer using SPI\&. The module test uses the LCD display to visualize the sensors output\&.  

.SS "Modules"

.in +1c
.ti -1c
.RI "\fBPublic\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
This is a test for for the sensor module consisting of TC72 temperature sensor and accelerometer using SPI\&. The module test uses the LCD display to visualize the sensors output\&. 


.SH "Author"
.PP 
Generated automatically by Doxygen for VROOM from the source code\&.
