.TH "D:/Dropbox/Skole Opgaver/ICT Engineering/7th Semester/Bachelor Project/Source Code/VROOM/VROOM_working/Tests/module/sensors/test_module_sensors.h" 3 "Sun Nov 30 2014" "Version v0.01" "VROOM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/Dropbox/Skole Opgaver/ICT Engineering/7th Semester/Bachelor Project/Source Code/VROOM/VROOM_working/Tests/module/sensors/test_module_sensors.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBsensors_init\fP (void)"
.br
.ti -1c
.RI "void \fBsensors_read_data\fP (void)"
.br
.ti -1c
.RI "void \fBsensors_print_data\fP (void)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
\fBAuthor:\fP
.RS 4
: Kenneth René Jensen : 0\&.1 
.RE
.PP

.PP
Definition in file \fBtest_module_sensors\&.h\fP\&.
.SH "Function Documentation"
.PP 
.SS "void sensors_init (void)"

.PP
\fBNote:\fP
.RS 4
NOT YET Complies MISRO 2004 standards 
.RE
.PP

.PP
Definition at line 22 of file test_module_sensors\&.c\&.
.SS "void sensors_print_data (void)"

.PP
Definition at line 39 of file test_module_sensors\&.c\&.
.SS "void sensors_read_data (void)"

.PP
Definition at line 31 of file test_module_sensors\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for VROOM from the source code\&.
