.TH "D:/Dropbox/Skole Opgaver/ICT Engineering/7th Semester/Bachelor Project/Source Code/VROOM/VROOM_working/Tests/module/uart/test_module_uart.c" 3 "Sun Nov 30 2014" "Version v0.01" "VROOM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/Dropbox/Skole Opgaver/ICT Engineering/7th Semester/Bachelor Project/Source Code/VROOM/VROOM_working/Tests/module/uart/test_module_uart.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <avr/io\&.h>\fP
.br
\fC#include <stdlib\&.h>\fP
.br
\fC#include <util/delay\&.h>\fP
.br
\fC#include 'test_module_uart\&.h'\fP
.br
\fC#include '\&.\&./\&.\&./\&.\&./data_comm/uart/uart\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBRECEIVED_DATA_LENGTH\fP   255"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "bool \fBtest_module_uart_run\fP (const char *__uart_test_string, const char *__uart_compare_string)"
.br
.RI "\fIStarts the testing routine for uart0 and uart1\&. \fP"
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define RECEIVED_DATA_LENGTH   255"
\fBtest_module_uart\&.c\fP
.PP
Created: 26-09-2014 15:48:21 Author: Andi Degn 
.PP
Definition at line 13 of file test_module_uart\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for VROOM from the source code\&.
