.TH "Module_test_sensors" 3 "Wed Dec 3 2014" "Version v0.01" "VROOM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Module_test_sensors \- 
This is a test for for the sensor module consisting of TC72 temperature sensor and accelerometer using SPI\&. The module test uses the LCD display to visualize the sensors output\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for VROOM from the source code\&.
