.TH "UART module test" 3 "Thu Dec 11 2014" "Version v0.01" "VROOM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UART module test \- 
.SS "Modules"

.in +1c
.ti -1c
.RI "\fBPrivate\fP"
.br
.ti -1c
.RI "\fBPublic\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
This tests the uart0 and uart 1 on the ATMega2560 by first sending a test string using uart0, receiving it in uart1 callback function and sending it back to uart0 in a callback function\&. Second it is tested again without using the callback feature by using the uart_read_char() function\&. Both tests received data is compared to the original string for validation\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for VROOM from the source code\&.
