.TH "D:/Dropbox/Skole Opgaver/ICT Engineering/7th Semester/Bachelor Project/Source Code/VROOM/VROOM_working/Tests/module/car_panel/test_module_car_panel.h" 3 "Thu Dec 11 2014" "Version v0.01" "VROOM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/Dropbox/Skole Opgaver/ICT Engineering/7th Semester/Bachelor Project/Source Code/VROOM/VROOM_working/Tests/module/car_panel/test_module_car_panel.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <stdint\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBinit_module_test_car_panel\fP (void)"
.br
.ti -1c
.RI "void \fBtest_status_LED\fP (uint8_t iterations)"
.br
.ti -1c
.RI "void \fBtest_control_LED\fP (uint8_t iterations)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
\fBAuthor:\fP
.RS 4
: Kenneth René Jensen : 0\&.1 
.RE
.PP

.PP
Definition in file \fBtest_module_car_panel\&.h\fP\&.
.SH "Function Documentation"
.PP 
.SS "void init_module_test_car_panel (void)"

.PP
Definition at line 14 of file test_module_car_panel\&.c\&.
.SS "void test_control_LED (uint8_titerations)"

.PP
Definition at line 34 of file test_module_car_panel\&.c\&.
.SS "void test_status_LED (uint8_titerations)"

.PP
Definition at line 20 of file test_module_car_panel\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for VROOM from the source code\&.
