.TH "D:/Dropbox/Skole Opgaver/ICT Engineering/7th Semester/Bachelor Project/Source Code/VROOM/VROOM_working/Tests/module/sensors/test_module_sensors.h" 3 "Thu Dec 11 2014" "Version v0.01" "VROOM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/Dropbox/Skole Opgaver/ICT Engineering/7th Semester/Bachelor Project/Source Code/VROOM/VROOM_working/Tests/module/sensors/test_module_sensors.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBsensors_init\fP (void)"
.br
.RI "\fIInitiates the sensor test\&. \fP"
.ti -1c
.RI "void \fBsensors_read_data\fP (void)"
.br
.RI "\fIReads the data from the sensors\&. \fP"
.ti -1c
.RI "void \fBsensors_print_data\fP (void)"
.br
.RI "\fIPrints the data from the sensors\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 

.PP
\fBAuthor:\fP
.RS 4
: Kenneth René Jensen : 0\&.1 
.RE
.PP

.PP
Definition in file \fBtest_module_sensors\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for VROOM from the source code\&.
