.TH "D:/Dropbox/Skole Opgaver/ICT Engineering/7th Semester/Bachelor Project/Source Code/VROOM/VROOM_working/util/timer/timer.c" 3 "Tue Dec 2 2014" "Version v0.01" "VROOM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/Dropbox/Skole Opgaver/ICT Engineering/7th Semester/Bachelor Project/Source Code/VROOM/VROOM_working/util/timer/timer.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <avr/interrupt\&.h>\fP
.br
\fC#include 'timer\&.h'\fP
.br
\fC#include '\&.\&./\&.\&./vroom_config\&.h'\fP
.br
\fC#include '\&.\&./\&.\&./sensors/sensor_scheduler\&.h'\fP
.br
\fC#include '\&.\&./\&.\&./accident_logic/accident_detection\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBTOP_VALUE\fP(frequency_in_hz, prescaler)   (\fBF_CPU\fP/(prescaler * frequency_in_hz)-1)"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBtimer1_init_CTC\fP (\fBTIMER_PRESCALER\fP prescaler, \fBTIMER_FREQUENCY\fP hz)"
.br
.RI "\fIInitiates timer 1 in CTC mode\&. \fP"
.ti -1c
.RI "void \fBtimer3_init_CTC\fP (\fBTIMER_PRESCALER\fP prescaler, \fBTIMER_FREQUENCY\fP hz)"
.br
.RI "\fIInitiates timer 3 in CTC mode\&. \fP"
.ti -1c
.RI "void \fBtimer3_start\fP (void)"
.br
.RI "\fIEnables interrupt for timer3\&. \fP"
.ti -1c
.RI "void \fBtimer3_stop\fP (void)"
.br
.RI "\fIDisables interrupt for timer3\&. \fP"
.ti -1c
.RI "void \fBtimer_pause_all\fP (void)"
.br
.RI "\fIDisables interrupt for timer1 and timer3\&. \fP"
.ti -1c
.RI "void \fBtimer_resume_all\fP (void)"
.br
.RI "\fIEnables interrupt for timer1 and timer3\&. \fP"
.ti -1c
.RI "\fBISR\fP (TIMER1_COMPA_vect)"
.br
.ti -1c
.RI "\fBISR\fP (TIMER3_COMPA_vect)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "static volatile uint8_t \fB_isr_counter\fP = 0"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
\fBAuthor:\fP
.RS 4
: Kenneth René Jensen : 0\&.3 
.RE
.PP

.PP
Definition in file \fBtimer\&.c\fP\&.
.SH "Macro Definition Documentation"
.PP 
.SS "#define TOP_VALUE(frequency_in_hz, prescaler)   (\fBF_CPU\fP/(prescaler * frequency_in_hz)-1)"
Macro for calculating the value for clock count based on frequency and prescaler 
.PP
Definition at line 22 of file timer\&.c\&.
.SH "Function Documentation"
.PP 
.SS "ISR (TIMER1_COMPA_vect)"

.PP
Definition at line 171 of file timer\&.c\&.
.SS "ISR (TIMER3_COMPA_vect)"

.PP
Definition at line 176 of file timer\&.c\&.
.SH "Variable Documentation"
.PP 
.SS "volatile uint8_t _isr_counter = 0\fC [static]\fP"

.PP
Definition at line 24 of file timer\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for VROOM from the source code\&.
