.TH "Timer" 3 "Sun Nov 30 2014" "Version v0.01" "VROOM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Timer \- 
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBTIMER_PRESCALER\fP { \fBTIMER_PS1\fP = 1, \fBTIMER_PS8\fP = 8, \fBTIMER_PS64\fP = 64, \fBTIMER_PS256\fP = 256, \fBTIMER_PS1024\fP = 1024 }"
.br
.RI "\fISpecifies the available clock dividers for Timer 1\&. \fP"
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBinit_Timer1_CTC\fP (\fBTIMER_PRESCALER\fP prescaler, \fBTIMER_FREQUENCY\fP hz)"
.br
.RI "\fIInitiates timer 1 in CTC mode\&. \fP"
.ti -1c
.RI "void \fBinit_Timer3_CTC\fP (\fBTIMER_PRESCALER\fP prescaler, \fBTIMER_FREQUENCY\fP hz)"
.br
.RI "\fIInitiates timer 3 in CTC mode\&. \fP"
.ti -1c
.RI "void \fBstart_timer3\fP (void)"
.br
.RI "\fIEnables interrupt for timer3\&. \fP"
.ti -1c
.RI "void \fBstop_timer3\fP (void)"
.br
.RI "\fIDisables interrupt for timer3\&. \fP"
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "uint32_t \fBSIM908_timeout_counter\fP"
.br
.RI "\fIextern variable which counts in timer3 ISR \fP"
.in -1c
.SH "Detailed Description"
.PP 
Setup of timer 1 to CTC mode for stating the scheduler\&. Setup of timer 3 to CTC mode for counting etc\&. used for timeout 
.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBTIMER_PRESCALER\fP"

.PP
Specifies the available clock dividers for Timer 1\&. 
.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fITIMER_PS1 \fP\fP
.TP
\fB\fITIMER_PS8 \fP\fP
.TP
\fB\fITIMER_PS64 \fP\fP
.TP
\fB\fITIMER_PS256 \fP\fP
.TP
\fB\fITIMER_PS1024 \fP\fP
.PP
Definition at line 22 of file timer\&.h\&.
.SH "Function Documentation"
.PP 
.SS "void init_Timer1_CTC (\fBTIMER_PRESCALER\fPprescaler, \fBTIMER_FREQUENCY\fPhz)"

.PP
Initiates timer 1 in CTC mode\&. 
.PP
\fBParameters:\fP
.RS 4
\fITIMER_PRESCALER\fP enum, TIMER_FREQUENCY enum 
.RE
.PP
\fBNote:\fP
.RS 4
Enables interrupt 
.RE
.PP

.PP
Definition at line 30 of file timer\&.c\&.
.SS "void init_Timer3_CTC (\fBTIMER_PRESCALER\fPprescaler, \fBTIMER_FREQUENCY\fPhz)"

.PP
Initiates timer 3 in CTC mode\&. 
.PP
\fBParameters:\fP
.RS 4
\fITIMER_PRESCALER\fP enum, TIMER_FREQUENCY enum 
.RE
.PP

.PP
Definition at line 84 of file timer\&.c\&.
.SS "void start_timer3 (void)"

.PP
Enables interrupt for timer3\&. 
.PP
Definition at line 134 of file timer\&.c\&.
.SS "void stop_timer3 (void)"

.PP
Disables interrupt for timer3\&. 
.PP
Definition at line 144 of file timer\&.c\&.
.SH "Variable Documentation"
.PP 
.SS "uint32_t SIM908_timeout_counter"

.PP
extern variable which counts in timer3 ISR 
.PP
Definition at line 22 of file timer\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for VROOM from the source code\&.
