.TH "UTC Seconds" 3 "Thu Dec 11 2014" "Version v0.01" "VROOM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UTC Seconds \- 
.PP
Calculates UTC seconds since EPOCH\&.  

.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBFIXED_TIME\fP"
.br
.RI "\fIstruct containing all parameters for UTC time \fP"
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "uint32_t \fBcalc_UTC_seconds\fP (\fBFIXED_TIME\fP *\fBbuf\fP)"
.br
.RI "\fICalculates UTC seconds since epoch\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Calculates UTC seconds since EPOCH\&. 


.PP
\fBNote:\fP
.RS 4
Complies MISRA 2004 standards 
.RE
.PP

.SH "Function Documentation"
.PP 
.SS "uint32_t calc_UTC_seconds (\fBFIXED_TIME\fP *buf)"

.PP
Calculates UTC seconds since epoch\&. Calculates UTC seconds since EPOCH 
.PP
Definition at line 24 of file time\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for VROOM from the source code\&.
