.TH "Private" 3 "Thu Dec 11 2014" "Version v0.01" "VROOM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Private \- 
.SS "Modules"

.in +1c
.ti -1c
.RI "\fBTimer top value equation\fP"
.br
.RI "\fIMacro for calculating the value for clock count based on frequency and prescaler\&. \fP"
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBISR\fP (TIMER1_COMPA_vect)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Function Documentation"
.PP 
.SS "ISR (TIMER1_COMPA_vect)"
Interrupt service routine which releases the scheduler 
.PP
Definition at line 123 of file timer\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for VROOM from the source code\&.
