.TH "D:/Dropbox/Skole Opgaver/ICT Engineering/7th Semester/Bachelor Project/Source Code/VROOM/VROOM_working/data_comm/uart/uart.c" 3 "Tue Dec 2 2014" "Version v0.01" "VROOM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/Dropbox/Skole Opgaver/ICT Engineering/7th Semester/Bachelor Project/Source Code/VROOM/VROOM_working/data_comm/uart/uart.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'uart\&.h'\fP
.br
\fC#include <stdlib\&.h>\fP
.br
\fC#include <util/delay\&.h>\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBUBRR_FACTOR_ASYNC_NORM\fP   16"
.br
.ti -1c
.RI "#define \fBUBRR_FACTOR_ASYNC_DOUBLE\fP   8"
.br
.ti -1c
.RI "#define \fBCALC_UBRR\fP(baud_rate, factor)   (((\fBF_CPU\fP / (factor * baud_rate)) - 1) + 0\&.5F)"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBuart0_setup_async\fP (\fBUART_MODE\fP __operational_mode, \fBUART_BAUD\fP __baud_rate, \fBUART_PARITY_MODE\fP __paraty_mode, \fBUART_STOP_BIT\fP __stop_bit, \fBUART_CHAR_SIZE\fP __char_size, void(*__callback_function_ptr)(char __data))"
.br
.RI "\fISets up the UART0 bus as asynchronous using supplied parameters\&. \fP"
.ti -1c
.RI "void \fBuart0_send_char\fP (char __data)"
.br
.RI "\fISends 1 (one) char of 'data' on the UART bus\&. \fP"
.ti -1c
.RI "void \fBuart0_send_string\fP (const char *__data)"
.br
.RI "\fISends a string (x no\&. of chars) of 'data' on the UART bus\&. \fP"
.ti -1c
.RI "void \fBuart0_send_data\fP (const char *__data, uint8_t __length)"
.br
.RI "\fISends data (based on length) of 'data' on the UART bus\&. \fP"
.ti -1c
.RI "uint16_t \fBuart0_read_char\fP (void)"
.br
.RI "\fIReads 1 (one) char of 'data' in the UART buffer\&. \fP"
.ti -1c
.RI "\fBISR\fP (USART0_UDRE_vect, ISR_BLOCK)"
.br
.ti -1c
.RI "\fBISR\fP (USART0_RX_vect, ISR_BLOCK)"
.br
.ti -1c
.RI "void \fBuart1_setup_async\fP (\fBUART_MODE\fP __operational_mode, \fBUART_BAUD\fP __baud_rate, \fBUART_PARITY_MODE\fP __paraty_mode, \fBUART_STOP_BIT\fP __stop_bit, \fBUART_CHAR_SIZE\fP __char_size, void(*__callback_function_ptr)(char __data))"
.br
.RI "\fISets up the UART1 bus as asynchronous using supplied parameters\&. \fP"
.ti -1c
.RI "void \fBuart1_send_char\fP (char __data)"
.br
.RI "\fISends 1 (one) char of 'data' on the UART bus\&. \fP"
.ti -1c
.RI "void \fBuart1_send_string\fP (const char *__data)"
.br
.RI "\fISends a string (x no\&. of chars) of 'data' on the UART bus\&. \fP"
.ti -1c
.RI "void \fBuart1_send_data\fP (const char *__data, uint8_t __length)"
.br
.RI "\fISends data (based on length) of 'data' on the UART bus\&. \fP"
.ti -1c
.RI "uint16_t \fBuart1_read_char\fP (void)"
.br
.RI "\fIReads 1 (one) char of 'data' in the UART buffer\&. \fP"
.ti -1c
.RI "\fBISR\fP (USART1_UDRE_vect, ISR_BLOCK)"
.br
.ti -1c
.RI "\fBISR\fP (USART1_RX_vect, ISR_BLOCK)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "static void(* \fB_callback_function0_ptr\fP )(char __data)"
.br
.ti -1c
.RI "static volatile char \fB_tx_buffer0\fP [\fBUART0_TX_BUFFER_SIZE\fP]"
.br
.ti -1c
.RI "static volatile uint8_t \fB_tx_buffer0_head\fP = 0U"
.br
.ti -1c
.RI "static volatile uint8_t \fB_tx_buffer0_tail\fP = 0U"
.br
.ti -1c
.RI "static volatile char \fB_rx_buffer0\fP [\fBUART0_RX_BUFFER_SIZE\fP]"
.br
.ti -1c
.RI "static volatile uint8_t \fB_rx_buffer0_head\fP = 0U"
.br
.ti -1c
.RI "static volatile uint8_t \fB_rx_buffer0_tail\fP = 0U"
.br
.ti -1c
.RI "static void(* \fB_callback_function1_ptr\fP )(char __data)"
.br
.ti -1c
.RI "static volatile char \fB_tx_buffer1\fP [\fBUART1_TX_BUFFER_SIZE\fP]"
.br
.ti -1c
.RI "static volatile uint8_t \fB_tx_buffer1_head\fP = 0U"
.br
.ti -1c
.RI "static volatile uint8_t \fB_tx_buffer1_tail\fP = 0U"
.br
.ti -1c
.RI "static volatile char \fB_rx_buffer1\fP [\fBUART1_RX_BUFFER_SIZE\fP]"
.br
.ti -1c
.RI "static volatile uint8_t \fB_rx_buffer1_head\fP = 0U"
.br
.ti -1c
.RI "static volatile uint8_t \fB_rx_buffer1_tail\fP = 0U"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "void(* _callback_function0_ptr)(char __data)\fC [static]\fP"

.PP
Definition at line 30 of file uart\&.c\&.
.SS "void(* _callback_function1_ptr)(char __data)\fC [static]\fP"

.PP
Definition at line 39 of file uart\&.c\&.
.SS "volatile char _rx_buffer0[\fBUART0_RX_BUFFER_SIZE\fP]\fC [static]\fP"

.PP
Definition at line 34 of file uart\&.c\&.
.SS "volatile uint8_t _rx_buffer0_head = 0U\fC [static]\fP"

.PP
Definition at line 35 of file uart\&.c\&.
.SS "volatile uint8_t _rx_buffer0_tail = 0U\fC [static]\fP"

.PP
Definition at line 36 of file uart\&.c\&.
.SS "volatile char _rx_buffer1[\fBUART1_RX_BUFFER_SIZE\fP]\fC [static]\fP"

.PP
Definition at line 43 of file uart\&.c\&.
.SS "volatile uint8_t _rx_buffer1_head = 0U\fC [static]\fP"

.PP
Definition at line 44 of file uart\&.c\&.
.SS "volatile uint8_t _rx_buffer1_tail = 0U\fC [static]\fP"

.PP
Definition at line 45 of file uart\&.c\&.
.SS "volatile char _tx_buffer0[\fBUART0_TX_BUFFER_SIZE\fP]\fC [static]\fP"

.PP
Definition at line 31 of file uart\&.c\&.
.SS "volatile uint8_t _tx_buffer0_head = 0U\fC [static]\fP"

.PP
Definition at line 32 of file uart\&.c\&.
.SS "volatile uint8_t _tx_buffer0_tail = 0U\fC [static]\fP"

.PP
Definition at line 33 of file uart\&.c\&.
.SS "volatile char _tx_buffer1[\fBUART1_TX_BUFFER_SIZE\fP]\fC [static]\fP"

.PP
Definition at line 40 of file uart\&.c\&.
.SS "volatile uint8_t _tx_buffer1_head = 0U\fC [static]\fP"

.PP
Definition at line 41 of file uart\&.c\&.
.SS "volatile uint8_t _tx_buffer1_tail = 0U\fC [static]\fP"

.PP
Definition at line 42 of file uart\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for VROOM from the source code\&.
