.TH "UART baud rate equation" 3 "Wed Dec 3 2014" "Version v0.01" "VROOM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UART baud rate equation \- 
.PP
defines for calculating the UBRR0 value  

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBCALC_UBRR\fP(baud_rate, factor)   (((\fBF_CPU\fP / (factor * baud_rate)) - 1) + 0\&.5F)"
.br
.in -1c
.SH "Detailed Description"
.PP 
defines for calculating the UBRR0 value 


.PP
\fBNote:\fP
.RS 4
0\&.5F is added to make sure rounding is done rather than truncating 
.RE
.PP

.SH "Macro Definition Documentation"
.PP 
.SS "#define CALC_UBRR(baud_rate, factor)   (((\fBF_CPU\fP / (factor * baud_rate)) - 1) + 0\&.5F)"

.PP
Definition at line 26 of file uart\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for VROOM from the source code\&.
