.TH "UART error codes" 3 "Thu Dec 11 2014" "Version v0.01" "VROOM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UART error codes \- 
.PP
define for UART return  

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBUART_NO_DATA\fP   0x100U"
.br
.ti -1c
.RI "#define \fBUART_READ_NOT_ALOWED\fP   0x200U"
.br
.ti -1c
.RI "#define \fBUART_BUFFER_OVERRUN\fP   0x300U"
.br
.in -1c
.SH "Detailed Description"
.PP 
define for UART return 


.SH "Macro Definition Documentation"
.PP 
.SS "#define UART_BUFFER_OVERRUN   0x300U"

.PP
Definition at line 54 of file uart\&.h\&.
.SS "#define UART_NO_DATA   0x100U"

.PP
Definition at line 52 of file uart\&.h\&.
.SS "#define UART_READ_NOT_ALOWED   0x200U"

.PP
Definition at line 53 of file uart\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for VROOM from the source code\&.
