.TH "UART Driver" 3 "Sun Nov 30 2014" "Version v0.01" "VROOM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UART Driver \- 
.SS "Modules"

.in +1c
.ti -1c
.RI "\fBPrivate\fP"
.br
.ti -1c
.RI "\fBPublic\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
This is a driver for the UART on the ATMEGA family processors
.PP
This is a driver for the UART0-1 on the ATMEGA family processors\&.
.br
 UART0:
.br
 RX: PE0
.br
 TX: PE1
.br
 
.br
 UART1:
.br
 RX: PD2
.br
 TX: PD3
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for VROOM from the source code\&.
