.TH "UART baud rate factor" 3 "Thu Dec 11 2014" "Version v0.01" "VROOM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UART baud rate factor \- 
.PP
defines for the factor used to calculate baud rate and UBRR0value  

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBUBRR_FACTOR_ASYNC_NORM\fP   16U"
.br
.ti -1c
.RI "#define \fBUBRR_FACTOR_ASYNC_DOUBLE\fP   8U"
.br
.in -1c
.SH "Detailed Description"
.PP 
defines for the factor used to calculate baud rate and UBRR0value 


.SH "Macro Definition Documentation"
.PP 
.SS "#define UBRR_FACTOR_ASYNC_DOUBLE   8U"

.PP
Definition at line 14 of file uart\&.c\&.
.SS "#define UBRR_FACTOR_ASYNC_NORM   16U"

.PP
Definition at line 13 of file uart\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for VROOM from the source code\&.
