.TH "UART Driver" 3 "Wed Dec 3 2014" "Version v0.01" "VROOM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UART Driver \- 
.PP
This is a driver for the UART0-1 on the ATMEGA family processors\&.  

.SS "Modules"

.in +1c
.ti -1c
.RI "\fBPublic\fP"
.br
.ti -1c
.RI "\fBPrivate\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
This is a driver for the UART0-1 on the ATMEGA family processors\&. 


.IP "\(bu" 2
UART0 pins:
.IP "  \(bu" 4
RX: PE0
.IP "  \(bu" 4
TX: PE1
.PP

.IP "\(bu" 2
UART1 pins:
.IP "  \(bu" 4
RX: PD2
.IP "  \(bu" 4
TX: PD3 
.PP

.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for VROOM from the source code\&.
