.TH "D:/Dropbox/Skole Opgaver/ICT Engineering/7th Semester/Bachelor Project/Source Code/VROOM/VROOM_working/Tests/unit/unit_test.c" 3 "Wed Dec 3 2014" "Version v0.01" "VROOM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/Dropbox/Skole Opgaver/ICT Engineering/7th Semester/Bachelor Project/Source Code/VROOM/VROOM_working/Tests/unit/unit_test.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'unit_test\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "char * \fBtest_tc72_calc\fP (void)"
.br
.RI "\fITest of function: \fBcalculate_temperature(uint8_t MSB, uint8_t LSB)\fP in \fBtc72\&.c\fP\&. \fP"
.ti -1c
.RI "char * \fBrun_all_tests\fP (void)"
.br
.RI "\fIRun all unit tests\&. \fP"
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "uint16_t \fBtests_run\fP = 0U"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
\fBAuthor:\fP
.RS 4
: Andi Degn 
.PP
: Kenneth René Jensen : 0\&.1 
.RE
.PP

.PP
Definition in file \fBunit_test\&.c\fP\&.
.SH "Variable Documentation"
.PP 
.SS "uint16_t tests_run = 0U"

.PP
\fBNote:\fP
.RS 4
Complies MISRO 2004 standards 
.RE
.PP

.PP
Definition at line 16 of file unit_test\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for VROOM from the source code\&.
