.TH "Accident detection parameters" 3 "Thu Dec 11 2014" "Version v0.01" "VROOM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Accident detection parameters \- 
.PP
Parameters for detecting an accident\&.  

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBCONFIG_SCHEDULER_FREQUENCY\fP   \fBTIMER_50HZ\fP	/**> Frequency of which the sensors are read in Hz */"
.br
.ti -1c
.RI "#define \fBCONFIG_ALARM_CRASH_NO_OF_READINGS\fP   5U			/**> Length of acceleration peek */"
.br
.ti -1c
.RI "#define \fBCONFIG_ALARM_CRASH_TRIGGER_VALUE\fP   400			/**> Total acceleration [G] in 1/100 resolution */"
.br
.ti -1c
.RI "#define \fBCONFIG_ALARM_FIRE_TRIGGER_DEGREE\fP   1\&.0F		/**> Temperature raise in Celsius degrees */"
.br
.ti -1c
.RI "#define \fBCONFIG_ALARM_FIRE_TRIGGER_TIME\fP   8000U		/**> Temperature raise time in 1ms resolution */"
.br
.ti -1c
.RI "#define \fBCONFIG_ALARM_FIRE_TEMP_INIT\fP   -100\&.0F		/**> Used to be sure there are two temperature readings before comparing values */"
.br
.ti -1c
.RI "#define \fBCONFIG_ALARM_BUTTON_PRESS_TIME\fP   30U"
.br
.in -1c
.SH "Detailed Description"
.PP 
Parameters for detecting an accident\&. 


.SH "Macro Definition Documentation"
.PP 
.SS "#define CONFIG_ALARM_BUTTON_PRESS_TIME   30U"

.PP
Definition at line 140 of file vroom_config\&.h\&.
.SS "#define CONFIG_ALARM_CRASH_NO_OF_READINGS   5U			/**> Length of acceleration peek */"

.PP
Definition at line 132 of file vroom_config\&.h\&.
.SS "#define CONFIG_ALARM_CRASH_TRIGGER_VALUE   400			/**> Total acceleration [G] in 1/100 resolution */"

.PP
Definition at line 133 of file vroom_config\&.h\&.
.SS "#define CONFIG_ALARM_FIRE_TEMP_INIT   -100\&.0F		/**> Used to be sure there are two temperature readings before comparing values */"

.PP
Definition at line 138 of file vroom_config\&.h\&.
.SS "#define CONFIG_ALARM_FIRE_TRIGGER_DEGREE   1\&.0F		/**> Temperature raise in Celsius degrees */"

.PP
Definition at line 135 of file vroom_config\&.h\&.
.SS "#define CONFIG_ALARM_FIRE_TRIGGER_TIME   8000U		/**> Temperature raise time in 1ms resolution */"

.PP
Definition at line 136 of file vroom_config\&.h\&.
.SS "#define CONFIG_SCHEDULER_FREQUENCY   \fBTIMER_50HZ\fP	/**> Frequency of which the sensors are read in Hz */"

.PP
Definition at line 130 of file vroom_config\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for VROOM from the source code\&.
