.TH "Data connection settings" 3 "Wed Dec 3 2014" "Version v0.01" "VROOM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Data connection settings \- 
.PP
Details for the data connection setup\&.  

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBCONFIG_FTP_SERVER_ADDRESS\fP   'ftp\&.andidegn\&.dk'"
.br
.ti -1c
.RI "#define \fBCONFIG_FTP_PORT\fP   '1404'"
.br
.ti -1c
.RI "#define \fBCONFIG_FTP_USER\fP   'VROOM'"
.br
.ti -1c
.RI "#define \fBCONFIG_FTP_PW\fP   '6198fg(/G6F/&5(!(!8gf87gMF\&.'"
.br
.ti -1c
.RI "#define \fBCONFIG_FTP_FILE_PATH\fP   '/'"
.br
.ti -1c
.RI "#define \fBCONFIG_FTP_FILE_SIZE\fP   '140' /* no of bytes */"
.br
.in -1c
.SH "Detailed Description"
.PP 
Details for the data connection setup\&. 


.SH "Macro Definition Documentation"
.PP 
.SS "#define CONFIG_FTP_FILE_PATH   '/'"

.PP
Definition at line 109 of file vroom_config\&.h\&.
.SS "#define CONFIG_FTP_FILE_SIZE   '140' /* no of bytes */"

.PP
Definition at line 110 of file vroom_config\&.h\&.
.SS "#define CONFIG_FTP_PORT   '1404'"

.PP
Definition at line 106 of file vroom_config\&.h\&.
.SS "#define CONFIG_FTP_PW   '6198fg(/G6F/&5(!(!8gf87gMF\&.'"

.PP
Definition at line 108 of file vroom_config\&.h\&.
.SS "#define CONFIG_FTP_SERVER_ADDRESS   'ftp\&.andidegn\&.dk'"

.PP
Definition at line 105 of file vroom_config\&.h\&.
.SS "#define CONFIG_FTP_USER   'VROOM'"

.PP
Definition at line 107 of file vroom_config\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for VROOM from the source code\&.
