.TH "Emergency number in use" 3 "Tue Dec 2 2014" "Version v0.01" "VROOM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Emergency number in use \- 
.PP
The emergency number used in the system\&.  

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBCONFIG_EMERGENCY_PHONE_NUMBER\fP   \fBCONFIG_PSAP_NUMBER_TEST_KENNETH\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
The emergency number used in the system\&. 


.SH "Macro Definition Documentation"
.PP 
.SS "#define CONFIG_EMERGENCY_PHONE_NUMBER   \fBCONFIG_PSAP_NUMBER_TEST_KENNETH\fP"

.PP
Definition at line 61 of file vroom_config\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for VROOM from the source code\&.
