.TH "Emergency phone numbers" 3 "Wed Dec 3 2014" "Version v0.01" "VROOM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Emergency phone numbers \- 
.PP
Lisg of emergency numbers, including 2 test numbers\&.  

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBCONFIG_PSAP_NUMBER_EUROPE\fP   '112'"
.br
.ti -1c
.RI "#define \fBCONFIG_PSAP_NUMBER_TEST_KENNETH\fP   '60192949' /* Only for testing */"
.br
.ti -1c
.RI "#define \fBCONFIG_PSAP_NUMBER_TEST_ANDI\fP   '60257898' /* Only for testing */"
.br
.in -1c
.SH "Detailed Description"
.PP 
Lisg of emergency numbers, including 2 test numbers\&. 


.SH "Macro Definition Documentation"
.PP 
.SS "#define CONFIG_PSAP_NUMBER_EUROPE   '112'"

.PP
Definition at line 82 of file vroom_config\&.h\&.
.SS "#define CONFIG_PSAP_NUMBER_TEST_ANDI   '60257898' /* Only for testing */"

.PP
Definition at line 84 of file vroom_config\&.h\&.
.SS "#define CONFIG_PSAP_NUMBER_TEST_KENNETH   '60192949' /* Only for testing */"

.PP
Definition at line 83 of file vroom_config\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for VROOM from the source code\&.
