.TH "ISP APN" 3 "Wed Dec 3 2014" "Version v0.01" "VROOM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ISP APN \- 
.PP
List of APN addresses for different ISP's\&.  

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBCONFIG_APN_TELIA\fP   'internet\&.mtelia\&.dk'"
.br
.ti -1c
.RI "#define \fBCONFIG_APN_CALLME\fP   'websp'"
.br
.ti -1c
.RI "#define \fBCONFIG_APN_TELENOR\fP   'internet'"
.br
.ti -1c
.RI "#define \fBCONFIG_APN_TDC\fP   'internet'"
.br
.in -1c
.SH "Detailed Description"
.PP 
List of APN addresses for different ISP's\&. 


.SH "Macro Definition Documentation"
.PP 
.SS "#define CONFIG_APN_CALLME   'websp'"

.PP
Definition at line 94 of file vroom_config\&.h\&.
.SS "#define CONFIG_APN_TDC   'internet'"

.PP
Definition at line 96 of file vroom_config\&.h\&.
.SS "#define CONFIG_APN_TELENOR   'internet'"

.PP
Definition at line 95 of file vroom_config\&.h\&.
.SS "#define CONFIG_APN_TELIA   'internet\&.mtelia\&.dk'"

.PP
Definition at line 93 of file vroom_config\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for VROOM from the source code\&.
