.TH "SIM908" 3 "Thu Dec 11 2014" "Version v0.01" "VROOM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SIM908 \- 
.PP
Port definition for the SIM908 module\&.  

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBSTK600\fP"
.br
.ti -1c
.RI "#define \fBCONFIG_PORT_DRIVER_PORT\fP   PORTE"
.br
.ti -1c
.RI "#define \fBCONFIG_PORT_GSM_PORT\fP   PORTE"
.br
.ti -1c
.RI "#define \fBCONFIG_PORT_GPS_PORT\fP   PORTE"
.br
.ti -1c
.RI "#define \fBCONFIG_PORT_GSM_ENABLE_PIN\fP   PE3"
.br
.ti -1c
.RI "#define \fBCONFIG_PORT_GPS_ENABLE_PIN\fP   PE4"
.br
.ti -1c
.RI "#define \fBCONFIG_PORT_CE_PIN\fP   PE5"
.br
.in -1c
.SH "Detailed Description"
.PP 
Port definition for the SIM908 module\&. 


.SH "Macro Definition Documentation"
.PP 
.SS "#define CONFIG_PORT_CE_PIN   PE5"

.PP
Definition at line 93 of file vroom_config\&.h\&.
.SS "#define CONFIG_PORT_DRIVER_PORT   PORTE"

.PP
Definition at line 88 of file vroom_config\&.h\&.
.SS "#define CONFIG_PORT_GPS_ENABLE_PIN   PE4"

.PP
Definition at line 92 of file vroom_config\&.h\&.
.SS "#define CONFIG_PORT_GPS_PORT   PORTE"

.PP
Definition at line 90 of file vroom_config\&.h\&.
.SS "#define CONFIG_PORT_GSM_ENABLE_PIN   PE3"

.PP
Definition at line 91 of file vroom_config\&.h\&.
.SS "#define CONFIG_PORT_GSM_PORT   PORTE"

.PP
Definition at line 89 of file vroom_config\&.h\&.
.SS "#define STK600"

.PP
Definition at line 86 of file vroom_config\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for VROOM from the source code\&.
