.TH "SPI" 3 "Thu Dec 11 2014" "Version v0.01" "VROOM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SPI \- 
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBCONFIG_PORT_DDR_SPI\fP   DDRB"
.br
.ti -1c
.RI "#define \fBCONFIG_PORT_SS\fP   PB0"
.br
.ti -1c
.RI "#define \fBCONFIG_PORT_SCK\fP   PB1"
.br
.ti -1c
.RI "#define \fBCONFIG_PORT_MOSI\fP   PB2"
.br
.ti -1c
.RI "#define \fBCONFIG_PORT_MISO\fP   PB3"
.br
.in -1c
.SH "Detailed Description"
.PP 
Defines for the ports and pins used by the SPI 
.SH "Macro Definition Documentation"
.PP 
.SS "#define CONFIG_PORT_DDR_SPI   DDRB"

.PP
Definition at line 66 of file vroom_config\&.h\&.
.SS "#define CONFIG_PORT_MISO   PB3"

.PP
Definition at line 70 of file vroom_config\&.h\&.
.SS "#define CONFIG_PORT_MOSI   PB2"

.PP
Definition at line 69 of file vroom_config\&.h\&.
.SS "#define CONFIG_PORT_SCK   PB1"

.PP
Definition at line 68 of file vroom_config\&.h\&.
.SS "#define CONFIG_PORT_SS   PB0"

.PP
Definition at line 67 of file vroom_config\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for VROOM from the source code\&.
