.TH "LCD display" 3 "Thu Dec 11 2014" "Version v0.01" "VROOM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
LCD display \- 
.PP
Port definition for the LCD display\&.  

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBCONFIG_PORT_LCD\fP   PORTL"
.br
.in -1c
.SH "Detailed Description"
.PP 
Port definition for the LCD display\&. 


.PP
\fBNote:\fP
.RS 4
This module is only used for debugging 
.RE
.PP

.SH "Macro Definition Documentation"
.PP 
.SS "#define CONFIG_PORT_LCD   PORTL"

.PP
Definition at line 111 of file vroom_config\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for VROOM from the source code\&.
