.TH "R2R LED" 3 "Thu Dec 11 2014" "Version v0.01" "VROOM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
R2R LED \- 
.PP
Port definition for the R2R LED module\&.  

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBCONFIG_PORT_R2R\fP   PORTH"
.br
.in -1c
.SH "Detailed Description"
.PP 
Port definition for the R2R LED module\&. 


.PP
\fBNote:\fP
.RS 4
This module is only used for debugging 
.RE
.PP

.SH "Macro Definition Documentation"
.PP 
.SS "#define CONFIG_PORT_R2R   PORTH"

.PP
Definition at line 120 of file vroom_config\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for VROOM from the source code\&.
