.TH "MCU port defines" 3 "Thu Dec 11 2014" "Version v0.01" "VROOM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MCU port defines \- 
.PP
Port definitions for the system\&.  

.SS "Modules"

.in +1c
.ti -1c
.RI "\fBSPI\fP"
.br
.ti -1c
.RI "\fBCar panel\fP"
.br
.RI "\fIPort definition for the car panel\&. \fP"
.ti -1c
.RI "\fBSIM908\fP"
.br
.RI "\fIPort definition for the SIM908 module\&. \fP"
.ti -1c
.RI "\fBLCD display\fP"
.br
.RI "\fIPort definition for the LCD display\&. \fP"
.ti -1c
.RI "\fBR2R LED\fP"
.br
.RI "\fIPort definition for the R2R LED module\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Port definitions for the system\&. 


.SH "Author"
.PP 
Generated automatically by Doxygen for VROOM from the source code\&.
