.TH "Test parameters" 3 "Wed Dec 3 2014" "Version v0.01" "VROOM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Test parameters \- 
.PP
Test parameters settings\&.  

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBCONFIG_VROOM_ID\fP   '60257898'"
.br
.ti -1c
.RI "#define \fBCONFIG_APN\fP   \fBCONFIG_APN_CALLME\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Test parameters settings\&. 


.SH "Macro Definition Documentation"
.PP 
.SS "#define CONFIG_APN   \fBCONFIG_APN_CALLME\fP"

.PP
Definition at line 125 of file vroom_config\&.h\&.
.SS "#define CONFIG_VROOM_ID   '60257898'"

.PP
Definition at line 124 of file vroom_config\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for VROOM from the source code\&.
