.TH "Vroom Config" 3 "Tue Dec 2 2014" "Version v0.01" "VROOM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Vroom Config \- 
.SS "Modules"

.in +1c
.ti -1c
.RI "\fBAccident detection parameters\fP"
.br
.RI "\fIParameters for detecting an accident\&. \fP"
.ti -1c
.RI "\fBMSD config parameters\fP"
.br
.RI "\fIDetails for the Minimun Set of Data (MSD) \fP"
.ti -1c
.RI "\fBEmergency number in use\fP"
.br
.RI "\fIThe emergency number used in the system\&. \fP"
.ti -1c
.RI "\fBEmergency phone numbers\fP"
.br
.RI "\fILisg of emergency numbers, including 2 test numbers\&. \fP"
.ti -1c
.RI "\fBISP APN\fP"
.br
.RI "\fIList of APN addresses for different ISP's\&. \fP"
.ti -1c
.RI "\fBData connection settings\fP"
.br
.RI "\fIDetails for the data connection setup\&. \fP"
.ti -1c
.RI "\fBTest parameters\fP"
.br
.RI "\fITest parameters settings\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Configuration file containing all adjustment and setup parameters for the whole system\&. 
.PP
\fBNote:\fP
.RS 4
NOT YET Complies MISRO 2004 standards 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for VROOM from the source code\&.
