.TH "D:/Dropbox/Skole Opgaver/ICT Engineering/7th Semester/Bachelor Project/Source Code/VROOM/VROOM_working/application/vroom_config.h" 3 "Thu Dec 11 2014" "Version v0.01" "VROOM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/Dropbox/Skole Opgaver/ICT Engineering/7th Semester/Bachelor Project/Source Code/VROOM/VROOM_working/application/vroom_config.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBYES\fP   1"
.br
.ti -1c
.RI "#define \fBNO\fP   0"
.br
.ti -1c
.RI "#define \fBANDI_TEST\fP   \fBNO\fP"
.br
.ti -1c
.RI "#define \fBKENNETH_TEST\fP   \fBYES\fP"
.br
.ti -1c
.RI "#define \fBDEBUG_UART_ENABLE\fP   /* UART1 (PD2/PD3) is used for RS232 communication with SIM908 module */"
.br
.ti -1c
.RI "#define \fBDEBUG_UART_ECHO\fP   /* Gives an echo from UART0 to UART1 */"
.br
.ti -1c
.RI "#define \fBDEBUG_LCD_ENABLE\fP   /* LCD should be connected to \fBPORT\fP L */"
.br
.ti -1c
.RI "#define \fBDEBUG_TASK_MEASURE\fP"
.br
.ti -1c
.RI "#define \fBDEBUG_ID_SIM908_START_MODULE\fP   3U"
.br
.ti -1c
.RI "#define \fBDEBUG_ID_SIM908_CMD_SEND\fP   8U"
.br
.ti -1c
.RI "#define \fBDEBUG_ID_SIM908_WAIT_FOR_RESPONSE\fP   1U"
.br
.ti -1c
.RI "#define \fBDEBUG_ID_SIM908_CALLBACK\fP   5U"
.br
.ti -1c
.RI "#define \fBDEBUG_ID_SENSOR_SCHEDULER_TEMP_REQ\fP   10U"
.br
.ti -1c
.RI "#define \fBDEBUG_ID_SENSOR_SCHEDULER_ACC_REQ\fP   11U"
.br
.ti -1c
.RI "#define \fBDEBUG_ID_SENSOR_SCHEDULER_READ\fP   12U"
.br
.ti -1c
.RI "#define \fBDEBUG_ID_ACCIDENT_CRASH_DETECTION\fP   14U"
.br
.ti -1c
.RI "#define \fBDEBUG_ID_ACCIDENT_FIRE_DETECTION\fP   15U"
.br
.ti -1c
.RI "#define \fBCONFIG_ENABLE_EMERGENCY_PHONE_CALL\fP"
.br
.ti -1c
.RI "#define \fBCONFIG_PORT_DDR_SPI\fP   DDRB"
.br
.ti -1c
.RI "#define \fBCONFIG_PORT_SS\fP   PB0"
.br
.ti -1c
.RI "#define \fBCONFIG_PORT_SCK\fP   PB1"
.br
.ti -1c
.RI "#define \fBCONFIG_PORT_MOSI\fP   PB2"
.br
.ti -1c
.RI "#define \fBCONFIG_PORT_MISO\fP   PB3"
.br
.ti -1c
.RI "#define \fBCONFIG_PORT_CAR_PANEL\fP   PORTJ"
.br
.ti -1c
.RI "#define \fBSTK600\fP"
.br
.ti -1c
.RI "#define \fBCONFIG_PORT_DRIVER_PORT\fP   PORTE"
.br
.ti -1c
.RI "#define \fBCONFIG_PORT_GSM_PORT\fP   PORTE"
.br
.ti -1c
.RI "#define \fBCONFIG_PORT_GPS_PORT\fP   PORTE"
.br
.ti -1c
.RI "#define \fBCONFIG_PORT_GSM_ENABLE_PIN\fP   PE3"
.br
.ti -1c
.RI "#define \fBCONFIG_PORT_GPS_ENABLE_PIN\fP   PE4"
.br
.ti -1c
.RI "#define \fBCONFIG_PORT_CE_PIN\fP   PE5"
.br
.ti -1c
.RI "#define \fBCONFIG_PORT_LCD\fP   PORTL"
.br
.ti -1c
.RI "#define \fBCONFIG_PORT_R2R\fP   PORTH"
.br
.ti -1c
.RI "#define \fBCONFIG_SCHEDULER_FREQUENCY\fP   \fBTIMER_50HZ\fP	/**> Frequency of which the sensors are read in Hz */"
.br
.ti -1c
.RI "#define \fBCONFIG_ALARM_CRASH_NO_OF_READINGS\fP   5U			/**> Length of acceleration peek */"
.br
.ti -1c
.RI "#define \fBCONFIG_ALARM_CRASH_TRIGGER_VALUE\fP   400			/**> Total acceleration [G] in 1/100 resolution */"
.br
.ti -1c
.RI "#define \fBCONFIG_ALARM_FIRE_TRIGGER_DEGREE\fP   1\&.0F		/**> Temperature raise in Celsius degrees */"
.br
.ti -1c
.RI "#define \fBCONFIG_ALARM_FIRE_TRIGGER_TIME\fP   8000U		/**> Temperature raise time in 1ms resolution */"
.br
.ti -1c
.RI "#define \fBCONFIG_ALARM_FIRE_TEMP_INIT\fP   -100\&.0F		/**> Used to be sure there are two temperature readings before comparing values */"
.br
.ti -1c
.RI "#define \fBCONFIG_ALARM_BUTTON_PRESS_TIME\fP   30U"
.br
.ti -1c
.RI "#define \fBCONFIG_MSD_FORMAT_VERSION\fP   2U"
.br
.ti -1c
.RI "#define \fBCONFIG_MSD_TEST_CALL\fP   true"
.br
.ti -1c
.RI "#define \fBCONFIG_MSD_VEHICLE_CLASS\fP   \fBAD_VEHICLE_CLASS_M\fP(1)	/**> M1 = No more than eight seats in addition to the driver’s seat, and having a maximum mass not exceeding 3\&.5 tons */"
.br
.ti -1c
.RI "#define \fBCONFIG_MSD_FUEL_TYPE\fP   \fBAD_FUEL_TYPE_GASOLINE\fP"
.br
.ti -1c
.RI "#define \fBCONFIG_MSD_VIN\fP   'W0L000036V1940069'"
.br
.ti -1c
.RI "#define \fBCONFIG_MSD_OPTIONAL_DATA_SIZE\fP   102U					/**> Calculated size based on total MSD size - compulsory data */"
.br
.ti -1c
.RI "#define \fBCONFIG_EMERGENCY_PHONE_NUMBER\fP   \fBCONFIG_PSAP_NUMBER_TEST_KENNETH\fP"
.br
.ti -1c
.RI "#define \fBCONFIG_PSAP_NUMBER_EUROPE\fP   '112'"
.br
.ti -1c
.RI "#define \fBCONFIG_PSAP_NUMBER_TEST_KENNETH\fP   '60192949' /* Only for testing */"
.br
.ti -1c
.RI "#define \fBCONFIG_PSAP_NUMBER_TEST_ANDI\fP   '60257898' /* Only for testing */"
.br
.ti -1c
.RI "#define \fBCONFIG_PSAP_NUMBER_TEST_KIM\fP   '28195667' /* Only for testing */"
.br
.ti -1c
.RI "#define \fBCONFIG_APN_TELIA\fP   'internet\&.mtelia\&.dk'"
.br
.ti -1c
.RI "#define \fBCONFIG_APN_CALLME\fP   'websp'"
.br
.ti -1c
.RI "#define \fBCONFIG_APN_TELENOR\fP   'internet'"
.br
.ti -1c
.RI "#define \fBCONFIG_APN_TDC\fP   'internet'"
.br
.ti -1c
.RI "#define \fBCONFIG_FTP_SERVER_ADDRESS\fP   'ftp\&.andidegn\&.dk'"
.br
.ti -1c
.RI "#define \fBCONFIG_FTP_PORT\fP   '1404'"
.br
.ti -1c
.RI "#define \fBCONFIG_FTP_USER\fP   'VROOM'"
.br
.ti -1c
.RI "#define \fBCONFIG_FTP_PW\fP   '6198fg(/G6F/&5(!(!8gf87gMF\&.'"
.br
.ti -1c
.RI "#define \fBCONFIG_FTP_FILE_PATH\fP   '/'"
.br
.ti -1c
.RI "#define \fBCONFIG_FTP_FILE_SIZE\fP   '140'			/* no of bytes */"
.br
.ti -1c
.RI "#define \fBCONFIG_PIN\fP   '5130'"
.br
.ti -1c
.RI "#define \fBCONFIG_VROOM_ID\fP   '60192949'"
.br
.ti -1c
.RI "#define \fBCONFIG_APN\fP   \fBCONFIG_APN_TDC\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
\fBAuthor:\fP
.RS 4
: Andi Degn 
.PP
: Kenneth René Jensen : 0\&.7 
.RE
.PP

.PP
Definition in file \fBvroom_config\&.h\fP\&.
.SH "Macro Definition Documentation"
.PP 
.SS "#define ANDI_TEST   \fBNO\fP"

.PP
Definition at line 30 of file vroom_config\&.h\&.
.SS "#define CONFIG_ENABLE_EMERGENCY_PHONE_CALL"

.PP
Definition at line 53 of file vroom_config\&.h\&.
.SS "#define DEBUG_ID_ACCIDENT_CRASH_DETECTION   14U"

.PP
Definition at line 49 of file vroom_config\&.h\&.
.SS "#define DEBUG_ID_ACCIDENT_FIRE_DETECTION   15U"

.PP
Definition at line 50 of file vroom_config\&.h\&.
.SS "#define DEBUG_ID_SENSOR_SCHEDULER_ACC_REQ   11U"

.PP
Definition at line 46 of file vroom_config\&.h\&.
.SS "#define DEBUG_ID_SENSOR_SCHEDULER_READ   12U"

.PP
Definition at line 47 of file vroom_config\&.h\&.
.SS "#define DEBUG_ID_SENSOR_SCHEDULER_TEMP_REQ   10U"

.PP
Definition at line 45 of file vroom_config\&.h\&.
.SS "#define DEBUG_ID_SIM908_CALLBACK   5U"

.PP
Definition at line 43 of file vroom_config\&.h\&.
.SS "#define DEBUG_ID_SIM908_CMD_SEND   8U"

.PP
Definition at line 41 of file vroom_config\&.h\&.
.SS "#define DEBUG_ID_SIM908_START_MODULE   3U"

.PP
Definition at line 40 of file vroom_config\&.h\&.
.SS "#define DEBUG_ID_SIM908_WAIT_FOR_RESPONSE   1U"

.PP
Definition at line 42 of file vroom_config\&.h\&.
.SS "#define DEBUG_LCD_ENABLE   /* LCD should be connected to \fBPORT\fP L */"

.PP
Definition at line 36 of file vroom_config\&.h\&.
.SS "#define DEBUG_TASK_MEASURE"

.PP
Definition at line 38 of file vroom_config\&.h\&.
.SS "#define DEBUG_UART_ECHO   /* Gives an echo from UART0 to UART1 */"

.PP
Definition at line 33 of file vroom_config\&.h\&.
.SS "#define DEBUG_UART_ENABLE   /* UART1 (PD2/PD3) is used for RS232 communication with SIM908 module */"

.PP
Definition at line 32 of file vroom_config\&.h\&.
.SS "#define KENNETH_TEST   \fBYES\fP"

.PP
Definition at line 31 of file vroom_config\&.h\&.
.SS "#define NO   0"

.PP
Definition at line 29 of file vroom_config\&.h\&.
.SS "#define YES   1"

.PP
Definition at line 28 of file vroom_config\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for VROOM from the source code\&.
